/**
 * This class is generated by jOOQ
 */
package DAO.mysql.generatedclasses.tables;


import DAO.mysql.generatedclasses.Ensinoindividualizado;
import DAO.mysql.generatedclasses.Keys;
import DAO.mysql.generatedclasses.tables.records.AlunoRecord;
import org.jooq.*;
import org.jooq.impl.TableImpl;

import javax.annotation.Generated;
import java.sql.Date;
import java.util.Arrays;
import java.util.List;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.7.0"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Aluno extends TableImpl<AlunoRecord> {

	private static final long serialVersionUID = 573141231;

	/**
	 * The reference instance of <code>ensinoindividualizado.aluno</code>
	 */
	public static final Aluno ALUNO = new Aluno();

	/**
	 * The class holding records for this type
	 */
	@Override
	public Class<AlunoRecord> getRecordType() {
		return AlunoRecord.class;
	}

	/**
	 * The column <code>ensinoindividualizado.aluno.idaluno</code>.
	 */
	public final TableField<AlunoRecord, Integer> IDALUNO = createField("idaluno", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

	/**
	 * The column <code>ensinoindividualizado.aluno.nome</code>.
	 */
	public final TableField<AlunoRecord, String> NOME = createField("nome", org.jooq.impl.SQLDataType.VARCHAR.length(100).nullable(false), this, "");

	/**
	 * The column <code>ensinoindividualizado.aluno.nascimento</code>.
	 */
	public final TableField<AlunoRecord, Date> NASCIMENTO = createField("nascimento", org.jooq.impl.SQLDataType.DATE.nullable(false), this, "");

	/**
	 * Create a <code>ensinoindividualizado.aluno</code> table reference
	 */
	public Aluno() {
		this("aluno", null);
	}

	/**
	 * Create an aliased <code>ensinoindividualizado.aluno</code> table reference
	 */
	public Aluno(String alias) {
		this(alias, ALUNO);
	}

	private Aluno(String alias, Table<AlunoRecord> aliased) {
		this(alias, aliased, null);
	}

	private Aluno(String alias, Table<AlunoRecord> aliased, Field<?>[] parameters) {
		super(alias, Ensinoindividualizado.ENSINOINDIVIDUALIZADO, aliased, parameters, "");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Identity<AlunoRecord, Integer> getIdentity() {
		return Keys.IDENTITY_ALUNO;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public UniqueKey<AlunoRecord> getPrimaryKey() {
		return Keys.KEY_ALUNO_PRIMARY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public List<UniqueKey<AlunoRecord>> getKeys() {
		return Arrays.<UniqueKey<AlunoRecord>>asList(Keys.KEY_ALUNO_PRIMARY);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Aluno as(String alias) {
		return new Aluno(alias, this);
	}

	/**
	 * Rename this table
	 */
	public Aluno rename(String name) {
		return new Aluno(name, null);
	}
}
