/**
 * This class is generated by jOOQ
 */
package DAO.mysql.generatedclasses.tables;


import DAO.mysql.generatedclasses.Ensinoindividualizado;
import DAO.mysql.generatedclasses.Keys;
import DAO.mysql.generatedclasses.tables.records.AudioRecord;
import org.jooq.*;
import org.jooq.impl.TableImpl;

import javax.annotation.Generated;
import java.util.Arrays;
import java.util.List;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.7.0"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Audio extends TableImpl<AudioRecord> {

	private static final long serialVersionUID = -407996970;

	/**
	 * The reference instance of <code>ensinoindividualizado.audio</code>
	 */
	public static final Audio AUDIO = new Audio();

	/**
	 * The class holding records for this type
	 */
	@Override
	public Class<AudioRecord> getRecordType() {
		return AudioRecord.class;
	}

	/**
	 * The column <code>ensinoindividualizado.audio.idaudio</code>.
	 */
	public final TableField<AudioRecord, Integer> IDAUDIO = createField("idaudio", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

	/**
	 * The column <code>ensinoindividualizado.audio.transcricao</code>.
	 */
	public final TableField<AudioRecord, String> TRANSCRICAO = createField("transcricao", org.jooq.impl.SQLDataType.VARCHAR.length(2048).nullable(false), this, "");

	/**
	 * The column <code>ensinoindividualizado.audio.som</code>.
	 */
	public final TableField<AudioRecord, byte[]> SOM = createField("som", org.jooq.impl.SQLDataType.BLOB.nullable(false), this, "");

	/**
	 * The column <code>ensinoindividualizado.audio.nome_original</code>.
	 */
	public final TableField<AudioRecord, String> NOME_ORIGINAL = createField("nome_original", org.jooq.impl.SQLDataType.VARCHAR.length(256).nullable(false), this, "");

	/**
	 * Create a <code>ensinoindividualizado.audio</code> table reference
	 */
	public Audio() {
		this("audio", null);
	}

	/**
	 * Create an aliased <code>ensinoindividualizado.audio</code> table reference
	 */
	public Audio(String alias) {
		this(alias, AUDIO);
	}

	private Audio(String alias, Table<AudioRecord> aliased) {
		this(alias, aliased, null);
	}

	private Audio(String alias, Table<AudioRecord> aliased, Field<?>[] parameters) {
		super(alias, Ensinoindividualizado.ENSINOINDIVIDUALIZADO, aliased, parameters, "");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Identity<AudioRecord, Integer> getIdentity() {
		return Keys.IDENTITY_AUDIO;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public UniqueKey<AudioRecord> getPrimaryKey() {
		return Keys.KEY_AUDIO_PRIMARY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public List<UniqueKey<AudioRecord>> getKeys() {
		return Arrays.<UniqueKey<AudioRecord>>asList(Keys.KEY_AUDIO_PRIMARY);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Audio as(String alias) {
		return new Audio(alias, this);
	}

	/**
	 * Rename this table
	 */
	public Audio rename(String name) {
		return new Audio(name, null);
	}
}
