/**
 * This class is generated by jOOQ
 */
package DAO.mysql.generatedclasses.tables;


import DAO.mysql.generatedclasses.Ensinoindividualizado;
import DAO.mysql.generatedclasses.Keys;
import DAO.mysql.generatedclasses.tables.records.AvaliacaoRecord;
import org.jooq.*;
import org.jooq.impl.TableImpl;

import javax.annotation.Generated;
import java.util.Arrays;
import java.util.List;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.7.0"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Avaliacao extends TableImpl<AvaliacaoRecord> {

	private static final long serialVersionUID = -129728817;

	/**
	 * The reference instance of <code>ensinoindividualizado.avaliacao</code>
	 */
	public static final Avaliacao AVALIACAO = new Avaliacao();

	/**
	 * The class holding records for this type
	 */
	@Override
	public Class<AvaliacaoRecord> getRecordType() {
		return AvaliacaoRecord.class;
	}

	/**
	 * The column <code>ensinoindividualizado.avaliacao.idavaliacao</code>.
	 */
	public final TableField<AvaliacaoRecord, Integer> IDAVALIACAO = createField("idavaliacao", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

	/**
	 * The column <code>ensinoindividualizado.avaliacao.descricao</code>.
	 */
	public final TableField<AvaliacaoRecord, String> DESCRICAO = createField("descricao", org.jooq.impl.SQLDataType.VARCHAR.length(1024).nullable(false), this, "");

	/**
	 * Create a <code>ensinoindividualizado.avaliacao</code> table reference
	 */
	public Avaliacao() {
		this("avaliacao", null);
	}

	/**
	 * Create an aliased <code>ensinoindividualizado.avaliacao</code> table reference
	 */
	public Avaliacao(String alias) {
		this(alias, AVALIACAO);
	}

	private Avaliacao(String alias, Table<AvaliacaoRecord> aliased) {
		this(alias, aliased, null);
	}

	private Avaliacao(String alias, Table<AvaliacaoRecord> aliased, Field<?>[] parameters) {
		super(alias, Ensinoindividualizado.ENSINOINDIVIDUALIZADO, aliased, parameters, "");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Identity<AvaliacaoRecord, Integer> getIdentity() {
		return Keys.IDENTITY_AVALIACAO;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public UniqueKey<AvaliacaoRecord> getPrimaryKey() {
		return Keys.KEY_AVALIACAO_PRIMARY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public List<UniqueKey<AvaliacaoRecord>> getKeys() {
		return Arrays.<UniqueKey<AvaliacaoRecord>>asList(Keys.KEY_AVALIACAO_PRIMARY);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Avaliacao as(String alias) {
		return new Avaliacao(alias, this);
	}

	/**
	 * Rename this table
	 */
	public Avaliacao rename(String name) {
		return new Avaliacao(name, null);
	}
}
