/**
 * This class is generated by jOOQ
 */
package DAO.mysql.generatedclasses.tables;


import DAO.mysql.generatedclasses.Ensinoindividualizado;
import DAO.mysql.generatedclasses.Keys;
import DAO.mysql.generatedclasses.tables.records.EnunciadoRecord;
import org.jooq.*;
import org.jooq.impl.TableImpl;

import javax.annotation.Generated;
import java.util.Arrays;
import java.util.List;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.7.0"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Enunciado extends TableImpl<EnunciadoRecord> {

	private static final long serialVersionUID = 1847473902;

	/**
	 * The reference instance of <code>ensinoindividualizado.enunciado</code>
	 */
	public static final Enunciado ENUNCIADO = new Enunciado();

	/**
	 * The class holding records for this type
	 */
	@Override
	public Class<EnunciadoRecord> getRecordType() {
		return EnunciadoRecord.class;
	}

	/**
	 * The column <code>ensinoindividualizado.enunciado.idenunciado</code>.
	 */
	public final TableField<EnunciadoRecord, Integer> IDENUNCIADO = createField("idenunciado", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

	/**
	 * The column <code>ensinoindividualizado.enunciado.descricao</code>.
	 */
	public final TableField<EnunciadoRecord, String> DESCRICAO = createField("descricao", org.jooq.impl.SQLDataType.VARCHAR.length(2048).nullable(false), this, "");

	/**
	 * The column <code>ensinoindividualizado.enunciado.idplaylist</code>.
	 */
	public final TableField<EnunciadoRecord, Integer> IDPLAYLIST = createField("idplaylist", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

	/**
	 * Create a <code>ensinoindividualizado.enunciado</code> table reference
	 */
	public Enunciado() {
		this("enunciado", null);
	}

	/**
	 * Create an aliased <code>ensinoindividualizado.enunciado</code> table reference
	 */
	public Enunciado(String alias) {
		this(alias, ENUNCIADO);
	}

	private Enunciado(String alias, Table<EnunciadoRecord> aliased) {
		this(alias, aliased, null);
	}

	private Enunciado(String alias, Table<EnunciadoRecord> aliased, Field<?>[] parameters) {
		super(alias, Ensinoindividualizado.ENSINOINDIVIDUALIZADO, aliased, parameters, "");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Identity<EnunciadoRecord, Integer> getIdentity() {
		return Keys.IDENTITY_ENUNCIADO;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public UniqueKey<EnunciadoRecord> getPrimaryKey() {
		return Keys.KEY_ENUNCIADO_PRIMARY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public List<UniqueKey<EnunciadoRecord>> getKeys() {
		return Arrays.<UniqueKey<EnunciadoRecord>>asList(Keys.KEY_ENUNCIADO_PRIMARY);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public List<ForeignKey<EnunciadoRecord, ?>> getReferences() {
		return Arrays.<ForeignKey<EnunciadoRecord, ?>>asList(Keys.FK_ENUNCIADO_PLAYLIST1);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Enunciado as(String alias) {
		return new Enunciado(alias, this);
	}

	/**
	 * Rename this table
	 */
	public Enunciado rename(String name) {
		return new Enunciado(name, null);
	}
}
