/**
 * This class is generated by jOOQ
 */
package DAO.mysql.generatedclasses.tables;


import DAO.mysql.generatedclasses.Ensinoindividualizado;
import DAO.mysql.generatedclasses.Keys;
import DAO.mysql.generatedclasses.tables.records.ImagemRecord;
import org.jooq.*;
import org.jooq.impl.TableImpl;

import javax.annotation.Generated;
import java.util.Arrays;
import java.util.List;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.7.0"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Imagem extends TableImpl<ImagemRecord> {

	private static final long serialVersionUID = 424314891;

	/**
	 * The reference instance of <code>ensinoindividualizado.imagem</code>
	 */
	public static final Imagem IMAGEM = new Imagem();

	/**
	 * The class holding records for this type
	 */
	@Override
	public Class<ImagemRecord> getRecordType() {
		return ImagemRecord.class;
	}

	/**
	 * The column <code>ensinoindividualizado.imagem.idimagem</code>.
	 */
	public final TableField<ImagemRecord, Integer> IDIMAGEM = createField("idimagem", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

	/**
	 * The column <code>ensinoindividualizado.imagem.imagem</code>.
	 */
	public final TableField<ImagemRecord, byte[]> IMAGEM_ = createField("imagem", org.jooq.impl.SQLDataType.BLOB.nullable(false), this, "");

	/**
	 * The column <code>ensinoindividualizado.imagem.nome_original</code>.
	 */
	public final TableField<ImagemRecord, String> NOME_ORIGINAL = createField("nome_original", org.jooq.impl.SQLDataType.VARCHAR.length(256).nullable(false), this, "");

	/**
	 * Create a <code>ensinoindividualizado.imagem</code> table reference
	 */
	public Imagem() {
		this("imagem", null);
	}

	/**
	 * Create an aliased <code>ensinoindividualizado.imagem</code> table reference
	 */
	public Imagem(String alias) {
		this(alias, IMAGEM);
	}

	private Imagem(String alias, Table<ImagemRecord> aliased) {
		this(alias, aliased, null);
	}

	private Imagem(String alias, Table<ImagemRecord> aliased, Field<?>[] parameters) {
		super(alias, Ensinoindividualizado.ENSINOINDIVIDUALIZADO, aliased, parameters, "");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Identity<ImagemRecord, Integer> getIdentity() {
		return Keys.IDENTITY_IMAGEM;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public UniqueKey<ImagemRecord> getPrimaryKey() {
		return Keys.KEY_IMAGEM_PRIMARY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public List<UniqueKey<ImagemRecord>> getKeys() {
		return Arrays.<UniqueKey<ImagemRecord>>asList(Keys.KEY_IMAGEM_PRIMARY);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Imagem as(String alias) {
		return new Imagem(alias, this);
	}

	/**
	 * Rename this table
	 */
	public Imagem rename(String name) {
		return new Imagem(name, null);
	}
}
