/**
 * This class is generated by jOOQ
 */
package DAO.mysql.generatedclasses.tables;


import DAO.mysql.generatedclasses.Ensinoindividualizado;
import DAO.mysql.generatedclasses.Keys;
import DAO.mysql.generatedclasses.tables.records.PalavraSilabaRecord;
import org.jooq.*;
import org.jooq.impl.TableImpl;

import javax.annotation.Generated;
import java.util.Arrays;
import java.util.List;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.7.0"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class PalavraSilaba extends TableImpl<PalavraSilabaRecord> {

	private static final long serialVersionUID = 1004852139;

	/**
	 * The reference instance of <code>ensinoindividualizado.palavra_silaba</code>
	 */
	public static final PalavraSilaba PALAVRA_SILABA = new PalavraSilaba();

	/**
	 * The class holding records for this type
	 */
	@Override
	public Class<PalavraSilabaRecord> getRecordType() {
		return PalavraSilabaRecord.class;
	}

	/**
	 * The column <code>ensinoindividualizado.palavra_silaba.palavra_idpalavra</code>.
	 */
	public final TableField<PalavraSilabaRecord, Integer> PALAVRA_IDPALAVRA = createField("palavra_idpalavra", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

	/**
	 * The column <code>ensinoindividualizado.palavra_silaba.silaba_idsilaba</code>.
	 */
	public final TableField<PalavraSilabaRecord, Integer> SILABA_IDSILABA = createField("silaba_idsilaba", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

	/**
	 * Create a <code>ensinoindividualizado.palavra_silaba</code> table reference
	 */
	public PalavraSilaba() {
		this("palavra_silaba", null);
	}

	/**
	 * Create an aliased <code>ensinoindividualizado.palavra_silaba</code> table reference
	 */
	public PalavraSilaba(String alias) {
		this(alias, PALAVRA_SILABA);
	}

	private PalavraSilaba(String alias, Table<PalavraSilabaRecord> aliased) {
		this(alias, aliased, null);
	}

	private PalavraSilaba(String alias, Table<PalavraSilabaRecord> aliased, Field<?>[] parameters) {
		super(alias, Ensinoindividualizado.ENSINOINDIVIDUALIZADO, aliased, parameters, "");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public UniqueKey<PalavraSilabaRecord> getPrimaryKey() {
		return Keys.KEY_PALAVRA_SILABA_PRIMARY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public List<UniqueKey<PalavraSilabaRecord>> getKeys() {
		return Arrays.<UniqueKey<PalavraSilabaRecord>>asList(Keys.KEY_PALAVRA_SILABA_PRIMARY);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public List<ForeignKey<PalavraSilabaRecord, ?>> getReferences() {
		return Arrays.<ForeignKey<PalavraSilabaRecord, ?>>asList(Keys.FK_PALAVRA_SILABA_PALAVRA1, Keys.FK_PALAVRA_SILABA_SILABA1);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public PalavraSilaba as(String alias) {
		return new PalavraSilaba(alias, this);
	}

	/**
	 * Rename this table
	 */
	public PalavraSilaba rename(String name) {
		return new PalavraSilaba(name, null);
	}
}
