/**
 * This class is generated by jOOQ
 */
package DAO.mysql.generatedclasses.tables;


import DAO.mysql.generatedclasses.Ensinoindividualizado;
import DAO.mysql.generatedclasses.Keys;
import DAO.mysql.generatedclasses.tables.records.PalavraRecord;
import org.jooq.*;
import org.jooq.impl.TableImpl;

import javax.annotation.Generated;
import java.util.Arrays;
import java.util.List;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.7.0"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Palavra extends TableImpl<PalavraRecord> {

	private static final long serialVersionUID = 739940965;

	/**
	 * The reference instance of <code>ensinoindividualizado.palavra</code>
	 */
	public static final Palavra PALAVRA = new Palavra();

	/**
	 * The class holding records for this type
	 */
	@Override
	public Class<PalavraRecord> getRecordType() {
		return PalavraRecord.class;
	}

	/**
	 * The column <code>ensinoindividualizado.palavra.idpalavra</code>.
	 */
	public final TableField<PalavraRecord, Integer> IDPALAVRA = createField("idpalavra", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

	/**
	 * The column <code>ensinoindividualizado.palavra.idcategoria</code>.
	 */
	public final TableField<PalavraRecord, Integer> IDCATEGORIA = createField("idcategoria", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

	/**
	 * The column <code>ensinoindividualizado.palavra.idaudio</code>.
	 */
	public final TableField<PalavraRecord, Integer> IDAUDIO = createField("idaudio", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

	/**
	 * The column <code>ensinoindividualizado.palavra.idimagem</code>.
	 */
	public final TableField<PalavraRecord, Integer> IDIMAGEM = createField("idimagem", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

	/**
	 * The column <code>ensinoindividualizado.palavra.idvideo</code>.
	 */
	public final TableField<PalavraRecord, Integer> IDVIDEO = createField("idvideo", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

	/**
	 * The column <code>ensinoindividualizado.palavra.palavra</code>.
	 */
	public final TableField<PalavraRecord, String> PALAVRA_ = createField("palavra", org.jooq.impl.SQLDataType.VARCHAR.length(50).nullable(false), this, "");

	/**
	 * Create a <code>ensinoindividualizado.palavra</code> table reference
	 */
	public Palavra() {
		this("palavra", null);
	}

	/**
	 * Create an aliased <code>ensinoindividualizado.palavra</code> table reference
	 */
	public Palavra(String alias) {
		this(alias, PALAVRA);
	}

	private Palavra(String alias, Table<PalavraRecord> aliased) {
		this(alias, aliased, null);
	}

	private Palavra(String alias, Table<PalavraRecord> aliased, Field<?>[] parameters) {
		super(alias, Ensinoindividualizado.ENSINOINDIVIDUALIZADO, aliased, parameters, "");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Identity<PalavraRecord, Integer> getIdentity() {
		return Keys.IDENTITY_PALAVRA;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public UniqueKey<PalavraRecord> getPrimaryKey() {
		return Keys.KEY_PALAVRA_PRIMARY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public List<UniqueKey<PalavraRecord>> getKeys() {
		return Arrays.<UniqueKey<PalavraRecord>>asList(Keys.KEY_PALAVRA_PRIMARY);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public List<ForeignKey<PalavraRecord, ?>> getReferences() {
		return Arrays.<ForeignKey<PalavraRecord, ?>>asList(Keys.FK_PALAVRA_CATEGORIA_PALAVRA1, Keys.FK_PALAVRA_AUDIO1, Keys.FK_PALAVRA_IMAGEM1, Keys.FK_PALAVRA_VIDEO1);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Palavra as(String alias) {
		return new Palavra(alias, this);
	}

	/**
	 * Rename this table
	 */
	public Palavra rename(String name) {
		return new Palavra(name, null);
	}
}
