/**
 * This class is generated by jOOQ
 */
package DAO.mysql.generatedclasses.tables;


import DAO.mysql.generatedclasses.Ensinoindividualizado;
import DAO.mysql.generatedclasses.Keys;
import DAO.mysql.generatedclasses.tables.records.SilabaRecord;
import org.jooq.*;
import org.jooq.impl.TableImpl;

import javax.annotation.Generated;
import java.util.Arrays;
import java.util.List;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.7.0"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Silaba extends TableImpl<SilabaRecord> {

	private static final long serialVersionUID = 1308831410;

	/**
	 * The reference instance of <code>ensinoindividualizado.silaba</code>
	 */
	public static final Silaba SILABA = new Silaba();

	/**
	 * The class holding records for this type
	 */
	@Override
	public Class<SilabaRecord> getRecordType() {
		return SilabaRecord.class;
	}

	/**
	 * The column <code>ensinoindividualizado.silaba.idsilaba</code>.
	 */
	public final TableField<SilabaRecord, Integer> IDSILABA = createField("idsilaba", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

	/**
	 * The column <code>ensinoindividualizado.silaba.silaba</code>.
	 */
	public final TableField<SilabaRecord, String> SILABA_ = createField("silaba", org.jooq.impl.SQLDataType.VARCHAR.length(10).nullable(false), this, "");

	/**
	 * Create a <code>ensinoindividualizado.silaba</code> table reference
	 */
	public Silaba() {
		this("silaba", null);
	}

	/**
	 * Create an aliased <code>ensinoindividualizado.silaba</code> table reference
	 */
	public Silaba(String alias) {
		this(alias, SILABA);
	}

	private Silaba(String alias, Table<SilabaRecord> aliased) {
		this(alias, aliased, null);
	}

	private Silaba(String alias, Table<SilabaRecord> aliased, Field<?>[] parameters) {
		super(alias, Ensinoindividualizado.ENSINOINDIVIDUALIZADO, aliased, parameters, "");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Identity<SilabaRecord, Integer> getIdentity() {
		return Keys.IDENTITY_SILABA;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public UniqueKey<SilabaRecord> getPrimaryKey() {
		return Keys.KEY_SILABA_PRIMARY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public List<UniqueKey<SilabaRecord>> getKeys() {
		return Arrays.<UniqueKey<SilabaRecord>>asList(Keys.KEY_SILABA_PRIMARY);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Silaba as(String alias) {
		return new Silaba(alias, this);
	}

	/**
	 * Rename this table
	 */
	public Silaba rename(String name) {
		return new Silaba(name, null);
	}
}
