/**
 * This class is generated by jOOQ
 */
package DAO.mysql.generatedclasses.tables;


import DAO.mysql.generatedclasses.Ensinoindividualizado;
import DAO.mysql.generatedclasses.Keys;
import DAO.mysql.generatedclasses.tables.records.TurmaRecord;
import org.jooq.*;
import org.jooq.impl.TableImpl;

import javax.annotation.Generated;
import java.util.Arrays;
import java.util.List;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.7.0"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Turma extends TableImpl<TurmaRecord> {

	private static final long serialVersionUID = -367171611;

	/**
	 * The reference instance of <code>ensinoindividualizado.turma</code>
	 */
	public static final Turma TURMA = new Turma();

	/**
	 * The class holding records for this type
	 */
	@Override
	public Class<TurmaRecord> getRecordType() {
		return TurmaRecord.class;
	}

	/**
	 * The column <code>ensinoindividualizado.turma.idturma</code>.
	 */
	public final TableField<TurmaRecord, Integer> IDTURMA = createField("idturma", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

	/**
	 * The column <code>ensinoindividualizado.turma.nome</code>.
	 */
	public final TableField<TurmaRecord, String> NOME = createField("nome", org.jooq.impl.SQLDataType.VARCHAR.length(100).nullable(false), this, "");

	/**
	 * The column <code>ensinoindividualizado.turma.descricao</code>.
	 */
	public final TableField<TurmaRecord, String> DESCRICAO = createField("descricao", org.jooq.impl.SQLDataType.VARCHAR.length(2048), this, "");

	/**
	 * Create a <code>ensinoindividualizado.turma</code> table reference
	 */
	public Turma() {
		this("turma", null);
	}

	/**
	 * Create an aliased <code>ensinoindividualizado.turma</code> table reference
	 */
	public Turma(String alias) {
		this(alias, TURMA);
	}

	private Turma(String alias, Table<TurmaRecord> aliased) {
		this(alias, aliased, null);
	}

	private Turma(String alias, Table<TurmaRecord> aliased, Field<?>[] parameters) {
		super(alias, Ensinoindividualizado.ENSINOINDIVIDUALIZADO, aliased, parameters, "");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Identity<TurmaRecord, Integer> getIdentity() {
		return Keys.IDENTITY_TURMA;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public UniqueKey<TurmaRecord> getPrimaryKey() {
		return Keys.KEY_TURMA_PRIMARY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public List<UniqueKey<TurmaRecord>> getKeys() {
		return Arrays.<UniqueKey<TurmaRecord>>asList(Keys.KEY_TURMA_PRIMARY);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Turma as(String alias) {
		return new Turma(alias, this);
	}

	/**
	 * Rename this table
	 */
	public Turma rename(String name) {
		return new Turma(name, null);
	}
}
