/**
 * This class is generated by jOOQ
 */
package DAO.mysql.generatedclasses.tables.records;


import DAO.mysql.generatedclasses.tables.Aluno;
import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record3;
import org.jooq.Row3;
import org.jooq.impl.UpdatableRecordImpl;

import javax.annotation.Generated;
import java.sql.Date;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.7.0"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class AlunoRecord extends UpdatableRecordImpl<AlunoRecord> implements Record3<Integer, String, Date> {

	private static final long serialVersionUID = -1937958538;

	/**
	 * Setter for <code>ensinoindividualizado.aluno.idaluno</code>.
	 */
	public void setIdaluno(Integer value) {
		setValue(0, value);
	}

	/**
	 * Getter for <code>ensinoindividualizado.aluno.idaluno</code>.
	 */
	public Integer getIdaluno() {
		return (Integer) getValue(0);
	}

	/**
	 * Setter for <code>ensinoindividualizado.aluno.nome</code>.
	 */
	public void setNome(String value) {
		setValue(1, value);
	}

	/**
	 * Getter for <code>ensinoindividualizado.aluno.nome</code>.
	 */
	public String getNome() {
		return (String) getValue(1);
	}

	/**
	 * Setter for <code>ensinoindividualizado.aluno.nascimento</code>.
	 */
	public void setNascimento(Date value) {
		setValue(2, value);
	}

	/**
	 * Getter for <code>ensinoindividualizado.aluno.nascimento</code>.
	 */
	public Date getNascimento() {
		return (Date) getValue(2);
	}

	// -------------------------------------------------------------------------
	// Primary key information
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Record1<Integer> key() {
		return (Record1) super.key();
	}

	// -------------------------------------------------------------------------
	// Record3 type implementation
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Row3<Integer, String, Date> fieldsRow() {
		return (Row3) super.fieldsRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Row3<Integer, String, Date> valuesRow() {
		return (Row3) super.valuesRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Integer> field1() {
		return Aluno.ALUNO.IDALUNO;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field2() {
		return Aluno.ALUNO.NOME;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Date> field3() {
		return Aluno.ALUNO.NASCIMENTO;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Integer value1() {
		return getIdaluno();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value2() {
		return getNome();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Date value3() {
		return getNascimento();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public AlunoRecord value1(Integer value) {
		setIdaluno(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public AlunoRecord value2(String value) {
		setNome(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public AlunoRecord value3(Date value) {
		setNascimento(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public AlunoRecord values(Integer value1, String value2, Date value3) {
		value1(value1);
		value2(value2);
		value3(value3);
		return this;
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached AlunoRecord
	 */
	public AlunoRecord() {
		super(Aluno.ALUNO);
	}

	/**
	 * Create a detached, initialised AlunoRecord
	 */
	public AlunoRecord(Integer idaluno, String nome, Date nascimento) {
		super(Aluno.ALUNO);

		setValue(0, idaluno);
		setValue(1, nome);
		setValue(2, nascimento);
	}
}
