/**
 * This class is generated by jOOQ
 */
package DAO.mysql.generatedclasses.tables.records;


import DAO.mysql.generatedclasses.tables.Audio;
import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record4;
import org.jooq.Row4;
import org.jooq.impl.UpdatableRecordImpl;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.7.0"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class AudioRecord extends UpdatableRecordImpl<AudioRecord> implements Record4<Integer, String, byte[], String> {

	private static final long serialVersionUID = 911797066;

	/**
	 * Setter for <code>ensinoindividualizado.audio.idaudio</code>.
	 */
	public void setIdaudio(Integer value) {
		setValue(0, value);
	}

	/**
	 * Getter for <code>ensinoindividualizado.audio.idaudio</code>.
	 */
	public Integer getIdaudio() {
		return (Integer) getValue(0);
	}

	/**
	 * Setter for <code>ensinoindividualizado.audio.transcricao</code>.
	 */
	public void setTranscricao(String value) {
		setValue(1, value);
	}

	/**
	 * Getter for <code>ensinoindividualizado.audio.transcricao</code>.
	 */
	public String getTranscricao() {
		return (String) getValue(1);
	}

	/**
	 * Setter for <code>ensinoindividualizado.audio.som</code>.
	 */
	public void setSom(byte[] value) {
		setValue(2, value);
	}

	/**
	 * Getter for <code>ensinoindividualizado.audio.som</code>.
	 */
	public byte[] getSom() {
		return (byte[]) getValue(2);
	}

	/**
	 * Setter for <code>ensinoindividualizado.audio.nome_original</code>.
	 */
	public void setNomeOriginal(String value) {
		setValue(3, value);
	}

	/**
	 * Getter for <code>ensinoindividualizado.audio.nome_original</code>.
	 */
	public String getNomeOriginal() {
		return (String) getValue(3);
	}

	// -------------------------------------------------------------------------
	// Primary key information
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Record1<Integer> key() {
		return (Record1) super.key();
	}

	// -------------------------------------------------------------------------
	// Record4 type implementation
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Row4<Integer, String, byte[], String> fieldsRow() {
		return (Row4) super.fieldsRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Row4<Integer, String, byte[], String> valuesRow() {
		return (Row4) super.valuesRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Integer> field1() {
		return Audio.AUDIO.IDAUDIO;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field2() {
		return Audio.AUDIO.TRANSCRICAO;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<byte[]> field3() {
		return Audio.AUDIO.SOM;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field4() {
		return Audio.AUDIO.NOME_ORIGINAL;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Integer value1() {
		return getIdaudio();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value2() {
		return getTranscricao();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public byte[] value3() {
		return getSom();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value4() {
		return getNomeOriginal();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public AudioRecord value1(Integer value) {
		setIdaudio(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public AudioRecord value2(String value) {
		setTranscricao(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public AudioRecord value3(byte[] value) {
		setSom(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public AudioRecord value4(String value) {
		setNomeOriginal(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public AudioRecord values(Integer value1, String value2, byte[] value3, String value4) {
		value1(value1);
		value2(value2);
		value3(value3);
		value4(value4);
		return this;
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached AudioRecord
	 */
	public AudioRecord() {
		super(Audio.AUDIO);
	}

	/**
	 * Create a detached, initialised AudioRecord
	 */
	public AudioRecord(Integer idaudio, String transcricao, byte[] som, String nomeOriginal) {
		super(Audio.AUDIO);

		setValue(0, idaudio);
		setValue(1, transcricao);
		setValue(2, som);
		setValue(3, nomeOriginal);
	}
}
