/**
 * This class is generated by jOOQ
 */
package DAO.mysql.generatedclasses.tables.records;


import DAO.mysql.generatedclasses.tables.AudioPlaylist;
import org.jooq.Field;
import org.jooq.Record2;
import org.jooq.Record3;
import org.jooq.Row3;
import org.jooq.impl.UpdatableRecordImpl;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.7.0"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class AudioPlaylistRecord extends UpdatableRecordImpl<AudioPlaylistRecord> implements Record3<Integer, Integer, Integer> {

	private static final long serialVersionUID = 1558132836;

	/**
	 * Setter for <code>ensinoindividualizado.audio_playlist.idplaylist</code>.
	 */
	public void setIdplaylist(Integer value) {
		setValue(0, value);
	}

	/**
	 * Getter for <code>ensinoindividualizado.audio_playlist.idplaylist</code>.
	 */
	public Integer getIdplaylist() {
		return (Integer) getValue(0);
	}

	/**
	 * Setter for <code>ensinoindividualizado.audio_playlist.idaudio</code>.
	 */
	public void setIdaudio(Integer value) {
		setValue(1, value);
	}

	/**
	 * Getter for <code>ensinoindividualizado.audio_playlist.idaudio</code>.
	 */
	public Integer getIdaudio() {
		return (Integer) getValue(1);
	}

	/**
	 * Setter for <code>ensinoindividualizado.audio_playlist.numero</code>.
	 */
	public void setNumero(Integer value) {
		setValue(2, value);
	}

	/**
	 * Getter for <code>ensinoindividualizado.audio_playlist.numero</code>.
	 */
	public Integer getNumero() {
		return (Integer) getValue(2);
	}

	// -------------------------------------------------------------------------
	// Primary key information
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Record2<Integer, Integer> key() {
		return (Record2) super.key();
	}

	// -------------------------------------------------------------------------
	// Record3 type implementation
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Row3<Integer, Integer, Integer> fieldsRow() {
		return (Row3) super.fieldsRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Row3<Integer, Integer, Integer> valuesRow() {
		return (Row3) super.valuesRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Integer> field1() {
		return AudioPlaylist.AUDIO_PLAYLIST.IDPLAYLIST;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Integer> field2() {
		return AudioPlaylist.AUDIO_PLAYLIST.IDAUDIO;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Integer> field3() {
		return AudioPlaylist.AUDIO_PLAYLIST.NUMERO;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Integer value1() {
		return getIdplaylist();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Integer value2() {
		return getIdaudio();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Integer value3() {
		return getNumero();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public AudioPlaylistRecord value1(Integer value) {
		setIdplaylist(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public AudioPlaylistRecord value2(Integer value) {
		setIdaudio(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public AudioPlaylistRecord value3(Integer value) {
		setNumero(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public AudioPlaylistRecord values(Integer value1, Integer value2, Integer value3) {
		value1(value1);
		value2(value2);
		value3(value3);
		return this;
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached AudioPlaylistRecord
	 */
	public AudioPlaylistRecord() {
		super(AudioPlaylist.AUDIO_PLAYLIST);
	}

	/**
	 * Create a detached, initialised AudioPlaylistRecord
	 */
	public AudioPlaylistRecord(Integer idplaylist, Integer idaudio, Integer numero) {
		super(AudioPlaylist.AUDIO_PLAYLIST);

		setValue(0, idplaylist);
		setValue(1, idaudio);
		setValue(2, numero);
	}
}
