/**
 * This class is generated by jOOQ
 */
package DAO.mysql.generatedclasses.tables.records;


import DAO.mysql.generatedclasses.tables.AvaliacaoBloco;
import org.jooq.Field;
import org.jooq.Record2;
import org.jooq.Row2;
import org.jooq.impl.UpdatableRecordImpl;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.7.0"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class AvaliacaoBlocoRecord extends UpdatableRecordImpl<AvaliacaoBlocoRecord> implements Record2<Integer, Integer> {

	private static final long serialVersionUID = -1667629926;

	/**
	 * Setter for <code>ensinoindividualizado.avaliacao_bloco.idavaliacao</code>.
	 */
	public void setIdavaliacao(Integer value) {
		setValue(0, value);
	}

	/**
	 * Getter for <code>ensinoindividualizado.avaliacao_bloco.idavaliacao</code>.
	 */
	public Integer getIdavaliacao() {
		return (Integer) getValue(0);
	}

	/**
	 * Setter for <code>ensinoindividualizado.avaliacao_bloco.idbloco</code>.
	 */
	public void setIdbloco(Integer value) {
		setValue(1, value);
	}

	/**
	 * Getter for <code>ensinoindividualizado.avaliacao_bloco.idbloco</code>.
	 */
	public Integer getIdbloco() {
		return (Integer) getValue(1);
	}

	// -------------------------------------------------------------------------
	// Primary key information
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Record2<Integer, Integer> key() {
		return (Record2) super.key();
	}

	// -------------------------------------------------------------------------
	// Record2 type implementation
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Row2<Integer, Integer> fieldsRow() {
		return (Row2) super.fieldsRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Row2<Integer, Integer> valuesRow() {
		return (Row2) super.valuesRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Integer> field1() {
		return AvaliacaoBloco.AVALIACAO_BLOCO.IDAVALIACAO;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Integer> field2() {
		return AvaliacaoBloco.AVALIACAO_BLOCO.IDBLOCO;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Integer value1() {
		return getIdavaliacao();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Integer value2() {
		return getIdbloco();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public AvaliacaoBlocoRecord value1(Integer value) {
		setIdavaliacao(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public AvaliacaoBlocoRecord value2(Integer value) {
		setIdbloco(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public AvaliacaoBlocoRecord values(Integer value1, Integer value2) {
		value1(value1);
		value2(value2);
		return this;
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached AvaliacaoBlocoRecord
	 */
	public AvaliacaoBlocoRecord() {
		super(AvaliacaoBloco.AVALIACAO_BLOCO);
	}

	/**
	 * Create a detached, initialised AvaliacaoBlocoRecord
	 */
	public AvaliacaoBlocoRecord(Integer idavaliacao, Integer idbloco) {
		super(AvaliacaoBloco.AVALIACAO_BLOCO);

		setValue(0, idavaliacao);
		setValue(1, idbloco);
	}
}
