/**
 * This class is generated by jOOQ
 */
package DAO.mysql.generatedclasses.tables.records;


import DAO.mysql.generatedclasses.tables.Avaliacao;
import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record2;
import org.jooq.Row2;
import org.jooq.impl.UpdatableRecordImpl;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.7.0"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class AvaliacaoRecord extends UpdatableRecordImpl<AvaliacaoRecord> implements Record2<Integer, String> {

	private static final long serialVersionUID = -602997743;

	/**
	 * Setter for <code>ensinoindividualizado.avaliacao.idavaliacao</code>.
	 */
	public void setIdavaliacao(Integer value) {
		setValue(0, value);
	}

	/**
	 * Getter for <code>ensinoindividualizado.avaliacao.idavaliacao</code>.
	 */
	public Integer getIdavaliacao() {
		return (Integer) getValue(0);
	}

	/**
	 * Setter for <code>ensinoindividualizado.avaliacao.descricao</code>.
	 */
	public void setDescricao(String value) {
		setValue(1, value);
	}

	/**
	 * Getter for <code>ensinoindividualizado.avaliacao.descricao</code>.
	 */
	public String getDescricao() {
		return (String) getValue(1);
	}

	// -------------------------------------------------------------------------
	// Primary key information
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Record1<Integer> key() {
		return (Record1) super.key();
	}

	// -------------------------------------------------------------------------
	// Record2 type implementation
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Row2<Integer, String> fieldsRow() {
		return (Row2) super.fieldsRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Row2<Integer, String> valuesRow() {
		return (Row2) super.valuesRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Integer> field1() {
		return Avaliacao.AVALIACAO.IDAVALIACAO;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field2() {
		return Avaliacao.AVALIACAO.DESCRICAO;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Integer value1() {
		return getIdavaliacao();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value2() {
		return getDescricao();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public AvaliacaoRecord value1(Integer value) {
		setIdavaliacao(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public AvaliacaoRecord value2(String value) {
		setDescricao(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public AvaliacaoRecord values(Integer value1, String value2) {
		value1(value1);
		value2(value2);
		return this;
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached AvaliacaoRecord
	 */
	public AvaliacaoRecord() {
		super(Avaliacao.AVALIACAO);
	}

	/**
	 * Create a detached, initialised AvaliacaoRecord
	 */
	public AvaliacaoRecord(Integer idavaliacao, String descricao) {
		super(Avaliacao.AVALIACAO);

		setValue(0, idavaliacao);
		setValue(1, descricao);
	}
}
