/**
 * This class is generated by jOOQ
 */
package DAO.mysql.generatedclasses.tables.records;


import DAO.mysql.generatedclasses.tables.Bloco;
import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record2;
import org.jooq.Row2;
import org.jooq.impl.UpdatableRecordImpl;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.7.0"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class BlocoRecord extends UpdatableRecordImpl<BlocoRecord> implements Record2<Integer, Integer> {

	private static final long serialVersionUID = -78414303;

	/**
	 * Setter for <code>ensinoindividualizado.bloco.idbloco</code>.
	 */
	public void setIdbloco(Integer value) {
		setValue(0, value);
	}

	/**
	 * Getter for <code>ensinoindividualizado.bloco.idbloco</code>.
	 */
	public Integer getIdbloco() {
		return (Integer) getValue(0);
	}

	/**
	 * Setter for <code>ensinoindividualizado.bloco.idtipobloco</code>.
	 */
	public void setIdtipobloco(Integer value) {
		setValue(1, value);
	}

	/**
	 * Getter for <code>ensinoindividualizado.bloco.idtipobloco</code>.
	 */
	public Integer getIdtipobloco() {
		return (Integer) getValue(1);
	}

	// -------------------------------------------------------------------------
	// Primary key information
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Record1<Integer> key() {
		return (Record1) super.key();
	}

	// -------------------------------------------------------------------------
	// Record2 type implementation
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Row2<Integer, Integer> fieldsRow() {
		return (Row2) super.fieldsRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Row2<Integer, Integer> valuesRow() {
		return (Row2) super.valuesRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Integer> field1() {
		return Bloco.BLOCO.IDBLOCO;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Integer> field2() {
		return Bloco.BLOCO.IDTIPOBLOCO;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Integer value1() {
		return getIdbloco();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Integer value2() {
		return getIdtipobloco();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public BlocoRecord value1(Integer value) {
		setIdbloco(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public BlocoRecord value2(Integer value) {
		setIdtipobloco(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public BlocoRecord values(Integer value1, Integer value2) {
		value1(value1);
		value2(value2);
		return this;
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached BlocoRecord
	 */
	public BlocoRecord() {
		super(Bloco.BLOCO);
	}

	/**
	 * Create a detached, initialised BlocoRecord
	 */
	public BlocoRecord(Integer idbloco, Integer idtipobloco) {
		super(Bloco.BLOCO);

		setValue(0, idbloco);
		setValue(1, idtipobloco);
	}
}
