/**
 * This class is generated by jOOQ
 */
package DAO.mysql.generatedclasses.tables.records;


import DAO.mysql.generatedclasses.tables.Categoria;
import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record3;
import org.jooq.Row3;
import org.jooq.impl.UpdatableRecordImpl;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.7.0"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class CategoriaRecord extends UpdatableRecordImpl<CategoriaRecord> implements Record3<Integer, String, String> {

	private static final long serialVersionUID = 80938393;

	/**
	 * Setter for <code>ensinoindividualizado.categoria.idcategoria</code>.
	 */
	public void setIdcategoria(Integer value) {
		setValue(0, value);
	}

	/**
	 * Getter for <code>ensinoindividualizado.categoria.idcategoria</code>.
	 */
	public Integer getIdcategoria() {
		return (Integer) getValue(0);
	}

	/**
	 * Setter for <code>ensinoindividualizado.categoria.nome</code>.
	 */
	public void setNome(String value) {
		setValue(1, value);
	}

	/**
	 * Getter for <code>ensinoindividualizado.categoria.nome</code>.
	 */
	public String getNome() {
		return (String) getValue(1);
	}

	/**
	 * Setter for <code>ensinoindividualizado.categoria.descricao</code>.
	 */
	public void setDescricao(String value) {
		setValue(2, value);
	}

	/**
	 * Getter for <code>ensinoindividualizado.categoria.descricao</code>.
	 */
	public String getDescricao() {
		return (String) getValue(2);
	}

	// -------------------------------------------------------------------------
	// Primary key information
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Record1<Integer> key() {
		return (Record1) super.key();
	}

	// -------------------------------------------------------------------------
	// Record3 type implementation
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Row3<Integer, String, String> fieldsRow() {
		return (Row3) super.fieldsRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Row3<Integer, String, String> valuesRow() {
		return (Row3) super.valuesRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Integer> field1() {
		return Categoria.CATEGORIA.IDCATEGORIA;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field2() {
		return Categoria.CATEGORIA.NOME;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field3() {
		return Categoria.CATEGORIA.DESCRICAO;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Integer value1() {
		return getIdcategoria();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value2() {
		return getNome();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value3() {
		return getDescricao();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public CategoriaRecord value1(Integer value) {
		setIdcategoria(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public CategoriaRecord value2(String value) {
		setNome(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public CategoriaRecord value3(String value) {
		setDescricao(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public CategoriaRecord values(Integer value1, String value2, String value3) {
		value1(value1);
		value2(value2);
		value3(value3);
		return this;
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached CategoriaRecord
	 */
	public CategoriaRecord() {
		super(Categoria.CATEGORIA);
	}

	/**
	 * Create a detached, initialised CategoriaRecord
	 */
	public CategoriaRecord(Integer idcategoria, String nome, String descricao) {
		super(Categoria.CATEGORIA);

		setValue(0, idcategoria);
		setValue(1, nome);
		setValue(2, descricao);
	}
}
