/**
 * This class is generated by jOOQ
 */
package DAO.mysql.generatedclasses.tables.records;


import DAO.mysql.generatedclasses.tables.Enunciado;
import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record3;
import org.jooq.Row3;
import org.jooq.impl.UpdatableRecordImpl;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.7.0"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class EnunciadoRecord extends UpdatableRecordImpl<EnunciadoRecord> implements Record3<Integer, String, Integer> {

	private static final long serialVersionUID = -1605286124;

	/**
	 * Setter for <code>ensinoindividualizado.enunciado.idenunciado</code>.
	 */
	public void setIdenunciado(Integer value) {
		setValue(0, value);
	}

	/**
	 * Getter for <code>ensinoindividualizado.enunciado.idenunciado</code>.
	 */
	public Integer getIdenunciado() {
		return (Integer) getValue(0);
	}

	/**
	 * Setter for <code>ensinoindividualizado.enunciado.descricao</code>.
	 */
	public void setDescricao(String value) {
		setValue(1, value);
	}

	/**
	 * Getter for <code>ensinoindividualizado.enunciado.descricao</code>.
	 */
	public String getDescricao() {
		return (String) getValue(1);
	}

	/**
	 * Setter for <code>ensinoindividualizado.enunciado.idplaylist</code>.
	 */
	public void setIdplaylist(Integer value) {
		setValue(2, value);
	}

	/**
	 * Getter for <code>ensinoindividualizado.enunciado.idplaylist</code>.
	 */
	public Integer getIdplaylist() {
		return (Integer) getValue(2);
	}

	// -------------------------------------------------------------------------
	// Primary key information
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Record1<Integer> key() {
		return (Record1) super.key();
	}

	// -------------------------------------------------------------------------
	// Record3 type implementation
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Row3<Integer, String, Integer> fieldsRow() {
		return (Row3) super.fieldsRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Row3<Integer, String, Integer> valuesRow() {
		return (Row3) super.valuesRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Integer> field1() {
		return Enunciado.ENUNCIADO.IDENUNCIADO;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field2() {
		return Enunciado.ENUNCIADO.DESCRICAO;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Integer> field3() {
		return Enunciado.ENUNCIADO.IDPLAYLIST;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Integer value1() {
		return getIdenunciado();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value2() {
		return getDescricao();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Integer value3() {
		return getIdplaylist();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public EnunciadoRecord value1(Integer value) {
		setIdenunciado(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public EnunciadoRecord value2(String value) {
		setDescricao(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public EnunciadoRecord value3(Integer value) {
		setIdplaylist(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public EnunciadoRecord values(Integer value1, String value2, Integer value3) {
		value1(value1);
		value2(value2);
		value3(value3);
		return this;
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached EnunciadoRecord
	 */
	public EnunciadoRecord() {
		super(Enunciado.ENUNCIADO);
	}

	/**
	 * Create a detached, initialised EnunciadoRecord
	 */
	public EnunciadoRecord(Integer idenunciado, String descricao, Integer idplaylist) {
		super(Enunciado.ENUNCIADO);

		setValue(0, idenunciado);
		setValue(1, descricao);
		setValue(2, idplaylist);
	}
}
