/**
 * This class is generated by jOOQ
 */
package DAO.mysql.generatedclasses.tables.records;


import DAO.mysql.generatedclasses.tables.Imagem;
import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record3;
import org.jooq.Row3;
import org.jooq.impl.UpdatableRecordImpl;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.7.0"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ImagemRecord extends UpdatableRecordImpl<ImagemRecord> implements Record3<Integer, byte[], String> {

	private static final long serialVersionUID = 1437391622;

	/**
	 * Setter for <code>ensinoindividualizado.imagem.idimagem</code>.
	 */
	public void setIdimagem(Integer value) {
		setValue(0, value);
	}

	/**
	 * Getter for <code>ensinoindividualizado.imagem.idimagem</code>.
	 */
	public Integer getIdimagem() {
		return (Integer) getValue(0);
	}

	/**
	 * Setter for <code>ensinoindividualizado.imagem.imagem</code>.
	 */
	public void setImagem(byte[] value) {
		setValue(1, value);
	}

	/**
	 * Getter for <code>ensinoindividualizado.imagem.imagem</code>.
	 */
	public byte[] getImagem() {
		return (byte[]) getValue(1);
	}

	/**
	 * Setter for <code>ensinoindividualizado.imagem.nome_original</code>.
	 */
	public void setNomeOriginal(String value) {
		setValue(2, value);
	}

	/**
	 * Getter for <code>ensinoindividualizado.imagem.nome_original</code>.
	 */
	public String getNomeOriginal() {
		return (String) getValue(2);
	}

	// -------------------------------------------------------------------------
	// Primary key information
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Record1<Integer> key() {
		return (Record1) super.key();
	}

	// -------------------------------------------------------------------------
	// Record3 type implementation
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Row3<Integer, byte[], String> fieldsRow() {
		return (Row3) super.fieldsRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Row3<Integer, byte[], String> valuesRow() {
		return (Row3) super.valuesRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Integer> field1() {
		return Imagem.IMAGEM.IDIMAGEM;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<byte[]> field2() {
		return Imagem.IMAGEM.IMAGEM_;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field3() {
		return Imagem.IMAGEM.NOME_ORIGINAL;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Integer value1() {
		return getIdimagem();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public byte[] value2() {
		return getImagem();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value3() {
		return getNomeOriginal();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public ImagemRecord value1(Integer value) {
		setIdimagem(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public ImagemRecord value2(byte[] value) {
		setImagem(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public ImagemRecord value3(String value) {
		setNomeOriginal(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public ImagemRecord values(Integer value1, byte[] value2, String value3) {
		value1(value1);
		value2(value2);
		value3(value3);
		return this;
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached ImagemRecord
	 */
	public ImagemRecord() {
		super(Imagem.IMAGEM);
	}

	/**
	 * Create a detached, initialised ImagemRecord
	 */
	public ImagemRecord(Integer idimagem, byte[] imagem, String nomeOriginal) {
		super(Imagem.IMAGEM);

		setValue(0, idimagem);
		setValue(1, imagem);
		setValue(2, nomeOriginal);
	}
}
