/**
 * This class is generated by jOOQ
 */
package DAO.mysql.generatedclasses.tables.records;


import DAO.mysql.generatedclasses.tables.PalavraSilaba;
import org.jooq.Field;
import org.jooq.Record2;
import org.jooq.Row2;
import org.jooq.impl.UpdatableRecordImpl;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.7.0"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class PalavraSilabaRecord extends UpdatableRecordImpl<PalavraSilabaRecord> implements Record2<Integer, Integer> {

	private static final long serialVersionUID = -299583506;

	/**
	 * Setter for <code>ensinoindividualizado.palavra_silaba.palavra_idpalavra</code>.
	 */
	public void setPalavraIdpalavra(Integer value) {
		setValue(0, value);
	}

	/**
	 * Getter for <code>ensinoindividualizado.palavra_silaba.palavra_idpalavra</code>.
	 */
	public Integer getPalavraIdpalavra() {
		return (Integer) getValue(0);
	}

	/**
	 * Setter for <code>ensinoindividualizado.palavra_silaba.silaba_idsilaba</code>.
	 */
	public void setSilabaIdsilaba(Integer value) {
		setValue(1, value);
	}

	/**
	 * Getter for <code>ensinoindividualizado.palavra_silaba.silaba_idsilaba</code>.
	 */
	public Integer getSilabaIdsilaba() {
		return (Integer) getValue(1);
	}

	// -------------------------------------------------------------------------
	// Primary key information
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Record2<Integer, Integer> key() {
		return (Record2) super.key();
	}

	// -------------------------------------------------------------------------
	// Record2 type implementation
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Row2<Integer, Integer> fieldsRow() {
		return (Row2) super.fieldsRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Row2<Integer, Integer> valuesRow() {
		return (Row2) super.valuesRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Integer> field1() {
		return PalavraSilaba.PALAVRA_SILABA.PALAVRA_IDPALAVRA;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Integer> field2() {
		return PalavraSilaba.PALAVRA_SILABA.SILABA_IDSILABA;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Integer value1() {
		return getPalavraIdpalavra();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Integer value2() {
		return getSilabaIdsilaba();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public PalavraSilabaRecord value1(Integer value) {
		setPalavraIdpalavra(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public PalavraSilabaRecord value2(Integer value) {
		setSilabaIdsilaba(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public PalavraSilabaRecord values(Integer value1, Integer value2) {
		value1(value1);
		value2(value2);
		return this;
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached PalavraSilabaRecord
	 */
	public PalavraSilabaRecord() {
		super(PalavraSilaba.PALAVRA_SILABA);
	}

	/**
	 * Create a detached, initialised PalavraSilabaRecord
	 */
	public PalavraSilabaRecord(Integer palavraIdpalavra, Integer silabaIdsilaba) {
		super(PalavraSilaba.PALAVRA_SILABA);

		setValue(0, palavraIdpalavra);
		setValue(1, silabaIdsilaba);
	}
}
