/**
 * This class is generated by jOOQ
 */
package DAO.mysql.generatedclasses.tables.records;


import DAO.mysql.generatedclasses.tables.Resposta;
import org.jooq.Field;
import org.jooq.Record5;
import org.jooq.Record6;
import org.jooq.Row6;
import org.jooq.impl.UpdatableRecordImpl;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.7.0"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class RespostaRecord extends UpdatableRecordImpl<RespostaRecord> implements Record6<Integer, Integer, Integer, Integer, Integer, Byte> {

	private static final long serialVersionUID = 586692212;

	/**
	 * Setter for <code>ensinoindividualizado.resposta.idResposta</code>.
	 */
	public void setIdresposta(Integer value) {
		setValue(0, value);
	}

	/**
	 * Getter for <code>ensinoindividualizado.resposta.idResposta</code>.
	 */
	public Integer getIdresposta() {
		return (Integer) getValue(0);
	}

	/**
	 * Setter for <code>ensinoindividualizado.resposta.realiza_idaluno</code>.
	 */
	public void setRealizaIdaluno(Integer value) {
		setValue(1, value);
	}

	/**
	 * Getter for <code>ensinoindividualizado.resposta.realiza_idaluno</code>.
	 */
	public Integer getRealizaIdaluno() {
		return (Integer) getValue(1);
	}

	/**
	 * Setter for <code>ensinoindividualizado.resposta.realiza_idavaliacao</code>.
	 */
	public void setRealizaIdavaliacao(Integer value) {
		setValue(2, value);
	}

	/**
	 * Getter for <code>ensinoindividualizado.resposta.realiza_idavaliacao</code>.
	 */
	public Integer getRealizaIdavaliacao() {
		return (Integer) getValue(2);
	}

	/**
	 * Setter for <code>ensinoindividualizado.resposta.idtentativa</code>.
	 */
	public void setIdtentativa(Integer value) {
		setValue(3, value);
	}

	/**
	 * Getter for <code>ensinoindividualizado.resposta.idtentativa</code>.
	 */
	public Integer getIdtentativa() {
		return (Integer) getValue(3);
	}

	/**
	 * Setter for <code>ensinoindividualizado.resposta.idalternativa</code>.
	 */
	public void setIdalternativa(Integer value) {
		setValue(4, value);
	}

	/**
	 * Getter for <code>ensinoindividualizado.resposta.idalternativa</code>.
	 */
	public Integer getIdalternativa() {
		return (Integer) getValue(4);
	}

	/**
	 * Setter for <code>ensinoindividualizado.resposta.acerto</code>. Se true, o aluno acertou a tentativa.
	 */
	public void setAcerto(Byte value) {
		setValue(5, value);
	}

	/**
	 * Getter for <code>ensinoindividualizado.resposta.acerto</code>. Se true, o aluno acertou a tentativa.
	 */
	public Byte getAcerto() {
		return (Byte) getValue(5);
	}

	// -------------------------------------------------------------------------
	// Primary key information
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Record5<Integer, Integer, Integer, Integer, Integer> key() {
		return (Record5) super.key();
	}

	// -------------------------------------------------------------------------
	// Record6 type implementation
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Row6<Integer, Integer, Integer, Integer, Integer, Byte> fieldsRow() {
		return (Row6) super.fieldsRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Row6<Integer, Integer, Integer, Integer, Integer, Byte> valuesRow() {
		return (Row6) super.valuesRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Integer> field1() {
		return Resposta.RESPOSTA.IDRESPOSTA;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Integer> field2() {
		return Resposta.RESPOSTA.REALIZA_IDALUNO;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Integer> field3() {
		return Resposta.RESPOSTA.REALIZA_IDAVALIACAO;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Integer> field4() {
		return Resposta.RESPOSTA.IDTENTATIVA;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Integer> field5() {
		return Resposta.RESPOSTA.IDALTERNATIVA;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Byte> field6() {
		return Resposta.RESPOSTA.ACERTO;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Integer value1() {
		return getIdresposta();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Integer value2() {
		return getRealizaIdaluno();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Integer value3() {
		return getRealizaIdavaliacao();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Integer value4() {
		return getIdtentativa();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Integer value5() {
		return getIdalternativa();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Byte value6() {
		return getAcerto();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public RespostaRecord value1(Integer value) {
		setIdresposta(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public RespostaRecord value2(Integer value) {
		setRealizaIdaluno(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public RespostaRecord value3(Integer value) {
		setRealizaIdavaliacao(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public RespostaRecord value4(Integer value) {
		setIdtentativa(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public RespostaRecord value5(Integer value) {
		setIdalternativa(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public RespostaRecord value6(Byte value) {
		setAcerto(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public RespostaRecord values(Integer value1, Integer value2, Integer value3, Integer value4, Integer value5, Byte value6) {
		value1(value1);
		value2(value2);
		value3(value3);
		value4(value4);
		value5(value5);
		value6(value6);
		return this;
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached RespostaRecord
	 */
	public RespostaRecord() {
		super(Resposta.RESPOSTA);
	}

	/**
	 * Create a detached, initialised RespostaRecord
	 */
	public RespostaRecord(Integer idresposta, Integer realizaIdaluno, Integer realizaIdavaliacao, Integer idtentativa, Integer idalternativa, Byte acerto) {
		super(Resposta.RESPOSTA);

		setValue(0, idresposta);
		setValue(1, realizaIdaluno);
		setValue(2, realizaIdavaliacao);
		setValue(3, idtentativa);
		setValue(4, idalternativa);
		setValue(5, acerto);
	}
}
