/**
 * This class is generated by jOOQ
 */
package DAO.mysql.generatedclasses.tables.records;


import DAO.mysql.generatedclasses.tables.Silaba;
import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record2;
import org.jooq.Row2;
import org.jooq.impl.UpdatableRecordImpl;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.7.0"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class SilabaRecord extends UpdatableRecordImpl<SilabaRecord> implements Record2<Integer, String> {

	private static final long serialVersionUID = -1032178424;

	/**
	 * Setter for <code>ensinoindividualizado.silaba.idsilaba</code>.
	 */
	public void setIdsilaba(Integer value) {
		setValue(0, value);
	}

	/**
	 * Getter for <code>ensinoindividualizado.silaba.idsilaba</code>.
	 */
	public Integer getIdsilaba() {
		return (Integer) getValue(0);
	}

	/**
	 * Setter for <code>ensinoindividualizado.silaba.silaba</code>.
	 */
	public void setSilaba(String value) {
		setValue(1, value);
	}

	/**
	 * Getter for <code>ensinoindividualizado.silaba.silaba</code>.
	 */
	public String getSilaba() {
		return (String) getValue(1);
	}

	// -------------------------------------------------------------------------
	// Primary key information
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Record1<Integer> key() {
		return (Record1) super.key();
	}

	// -------------------------------------------------------------------------
	// Record2 type implementation
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Row2<Integer, String> fieldsRow() {
		return (Row2) super.fieldsRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Row2<Integer, String> valuesRow() {
		return (Row2) super.valuesRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Integer> field1() {
		return Silaba.SILABA.IDSILABA;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field2() {
		return Silaba.SILABA.SILABA_;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Integer value1() {
		return getIdsilaba();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value2() {
		return getSilaba();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public SilabaRecord value1(Integer value) {
		setIdsilaba(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public SilabaRecord value2(String value) {
		setSilaba(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public SilabaRecord values(Integer value1, String value2) {
		value1(value1);
		value2(value2);
		return this;
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached SilabaRecord
	 */
	public SilabaRecord() {
		super(Silaba.SILABA);
	}

	/**
	 * Create a detached, initialised SilabaRecord
	 */
	public SilabaRecord(Integer idsilaba, String silaba) {
		super(Silaba.SILABA);

		setValue(0, idsilaba);
		setValue(1, silaba);
	}
}
