/**
 * This class is generated by jOOQ
 */
package DAO.mysql.generatedclasses.tables.records;


import DAO.mysql.generatedclasses.tables.Tentativa;
import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record3;
import org.jooq.Row3;
import org.jooq.impl.UpdatableRecordImpl;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.7.0"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TentativaRecord extends UpdatableRecordImpl<TentativaRecord> implements Record3<Integer, Integer, Integer> {

	private static final long serialVersionUID = 617920590;

	/**
	 * Setter for <code>ensinoindividualizado.tentativa.idtentativa</code>.
	 */
	public void setIdtentativa(Integer value) {
		setValue(0, value);
	}

	/**
	 * Getter for <code>ensinoindividualizado.tentativa.idtentativa</code>.
	 */
	public Integer getIdtentativa() {
		return (Integer) getValue(0);
	}

	/**
	 * Setter for <code>ensinoindividualizado.tentativa.idbloco</code>.
	 */
	public void setIdbloco(Integer value) {
		setValue(1, value);
	}

	/**
	 * Getter for <code>ensinoindividualizado.tentativa.idbloco</code>.
	 */
	public Integer getIdbloco() {
		return (Integer) getValue(1);
	}

	/**
	 * Setter for <code>ensinoindividualizado.tentativa.idenunciado</code>.
	 */
	public void setIdenunciado(Integer value) {
		setValue(2, value);
	}

	/**
	 * Getter for <code>ensinoindividualizado.tentativa.idenunciado</code>.
	 */
	public Integer getIdenunciado() {
		return (Integer) getValue(2);
	}

	// -------------------------------------------------------------------------
	// Primary key information
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Record1<Integer> key() {
		return (Record1) super.key();
	}

	// -------------------------------------------------------------------------
	// Record3 type implementation
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Row3<Integer, Integer, Integer> fieldsRow() {
		return (Row3) super.fieldsRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Row3<Integer, Integer, Integer> valuesRow() {
		return (Row3) super.valuesRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Integer> field1() {
		return Tentativa.TENTATIVA.IDTENTATIVA;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Integer> field2() {
		return Tentativa.TENTATIVA.IDBLOCO;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Integer> field3() {
		return Tentativa.TENTATIVA.IDENUNCIADO;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Integer value1() {
		return getIdtentativa();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Integer value2() {
		return getIdbloco();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Integer value3() {
		return getIdenunciado();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public TentativaRecord value1(Integer value) {
		setIdtentativa(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public TentativaRecord value2(Integer value) {
		setIdbloco(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public TentativaRecord value3(Integer value) {
		setIdenunciado(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public TentativaRecord values(Integer value1, Integer value2, Integer value3) {
		value1(value1);
		value2(value2);
		value3(value3);
		return this;
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached TentativaRecord
	 */
	public TentativaRecord() {
		super(Tentativa.TENTATIVA);
	}

	/**
	 * Create a detached, initialised TentativaRecord
	 */
	public TentativaRecord(Integer idtentativa, Integer idbloco, Integer idenunciado) {
		super(Tentativa.TENTATIVA);

		setValue(0, idtentativa);
		setValue(1, idbloco);
		setValue(2, idenunciado);
	}
}
