/**
 * This class is generated by jOOQ
 */
package DAO.mysql.generatedclasses.tables.records;


import DAO.mysql.generatedclasses.tables.Tipobloco;
import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record2;
import org.jooq.Row2;
import org.jooq.impl.UpdatableRecordImpl;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.7.0"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TipoblocoRecord extends UpdatableRecordImpl<TipoblocoRecord> implements Record2<Integer, String> {

	private static final long serialVersionUID = 1025157077;

	/**
	 * Setter for <code>ensinoindividualizado.tipobloco.idtipobloco</code>.
	 */
	public void setIdtipobloco(Integer value) {
		setValue(0, value);
	}

	/**
	 * Getter for <code>ensinoindividualizado.tipobloco.idtipobloco</code>.
	 */
	public Integer getIdtipobloco() {
		return (Integer) getValue(0);
	}

	/**
	 * Setter for <code>ensinoindividualizado.tipobloco.descricao</code>.
	 */
	public void setDescricao(String value) {
		setValue(1, value);
	}

	/**
	 * Getter for <code>ensinoindividualizado.tipobloco.descricao</code>.
	 */
	public String getDescricao() {
		return (String) getValue(1);
	}

	// -------------------------------------------------------------------------
	// Primary key information
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Record1<Integer> key() {
		return (Record1) super.key();
	}

	// -------------------------------------------------------------------------
	// Record2 type implementation
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Row2<Integer, String> fieldsRow() {
		return (Row2) super.fieldsRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Row2<Integer, String> valuesRow() {
		return (Row2) super.valuesRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Integer> field1() {
		return Tipobloco.TIPOBLOCO.IDTIPOBLOCO;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field2() {
		return Tipobloco.TIPOBLOCO.DESCRICAO;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Integer value1() {
		return getIdtipobloco();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value2() {
		return getDescricao();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public TipoblocoRecord value1(Integer value) {
		setIdtipobloco(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public TipoblocoRecord value2(String value) {
		setDescricao(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public TipoblocoRecord values(Integer value1, String value2) {
		value1(value1);
		value2(value2);
		return this;
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached TipoblocoRecord
	 */
	public TipoblocoRecord() {
		super(Tipobloco.TIPOBLOCO);
	}

	/**
	 * Create a detached, initialised TipoblocoRecord
	 */
	public TipoblocoRecord(Integer idtipobloco, String descricao) {
		super(Tipobloco.TIPOBLOCO);

		setValue(0, idtipobloco);
		setValue(1, descricao);
	}
}
