/**
 * This class is generated by jOOQ
 */
package DAO.mysql.generatedclasses.tables.records;


import DAO.mysql.generatedclasses.tables.Turma;
import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record3;
import org.jooq.Row3;
import org.jooq.impl.UpdatableRecordImpl;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.7.0"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TurmaRecord extends UpdatableRecordImpl<TurmaRecord> implements Record3<Integer, String, String> {

	private static final long serialVersionUID = -538540539;

	/**
	 * Setter for <code>ensinoindividualizado.turma.idturma</code>.
	 */
	public void setIdturma(Integer value) {
		setValue(0, value);
	}

	/**
	 * Getter for <code>ensinoindividualizado.turma.idturma</code>.
	 */
	public Integer getIdturma() {
		return (Integer) getValue(0);
	}

	/**
	 * Setter for <code>ensinoindividualizado.turma.nome</code>.
	 */
	public void setNome(String value) {
		setValue(1, value);
	}

	/**
	 * Getter for <code>ensinoindividualizado.turma.nome</code>.
	 */
	public String getNome() {
		return (String) getValue(1);
	}

	/**
	 * Setter for <code>ensinoindividualizado.turma.descricao</code>.
	 */
	public void setDescricao(String value) {
		setValue(2, value);
	}

	/**
	 * Getter for <code>ensinoindividualizado.turma.descricao</code>.
	 */
	public String getDescricao() {
		return (String) getValue(2);
	}

	// -------------------------------------------------------------------------
	// Primary key information
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Record1<Integer> key() {
		return (Record1) super.key();
	}

	// -------------------------------------------------------------------------
	// Record3 type implementation
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Row3<Integer, String, String> fieldsRow() {
		return (Row3) super.fieldsRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Row3<Integer, String, String> valuesRow() {
		return (Row3) super.valuesRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Integer> field1() {
		return Turma.TURMA.IDTURMA;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field2() {
		return Turma.TURMA.NOME;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field3() {
		return Turma.TURMA.DESCRICAO;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Integer value1() {
		return getIdturma();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value2() {
		return getNome();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value3() {
		return getDescricao();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public TurmaRecord value1(Integer value) {
		setIdturma(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public TurmaRecord value2(String value) {
		setNome(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public TurmaRecord value3(String value) {
		setDescricao(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public TurmaRecord values(Integer value1, String value2, String value3) {
		value1(value1);
		value2(value2);
		value3(value3);
		return this;
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached TurmaRecord
	 */
	public TurmaRecord() {
		super(Turma.TURMA);
	}

	/**
	 * Create a detached, initialised TurmaRecord
	 */
	public TurmaRecord(Integer idturma, String nome, String descricao) {
		super(Turma.TURMA);

		setValue(0, idturma);
		setValue(1, nome);
		setValue(2, descricao);
	}
}
