/**
 * This class is generated by jOOQ
 */
package DAO.mysql.generatedclasses;


import DAO.mysql.generatedclasses.tables.*;
import DAO.mysql.generatedclasses.tables.records.*;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.UniqueKey;
import org.jooq.impl.AbstractKeys;

import javax.annotation.Generated;


/**
 * A class modelling foreign key relationships between tables of the <code>ensinoindividualizado</code> 
 * schema
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.7.0"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Keys {

	// -------------------------------------------------------------------------
	// IDENTITY definitions
	// -------------------------------------------------------------------------

	public static final Identity<AlternativaRecord, Integer> IDENTITY_ALTERNATIVA = Identities0.IDENTITY_ALTERNATIVA;
	public static final Identity<AlunoRecord, Integer> IDENTITY_ALUNO = Identities0.IDENTITY_ALUNO;
	public static final Identity<AudioRecord, Integer> IDENTITY_AUDIO = Identities0.IDENTITY_AUDIO;
	public static final Identity<AvaliacaoRecord, Integer> IDENTITY_AVALIACAO = Identities0.IDENTITY_AVALIACAO;
	public static final Identity<BlocoRecord, Integer> IDENTITY_BLOCO = Identities0.IDENTITY_BLOCO;
	public static final Identity<CategoriaRecord, Integer> IDENTITY_CATEGORIA = Identities0.IDENTITY_CATEGORIA;
	public static final Identity<EnunciadoRecord, Integer> IDENTITY_ENUNCIADO = Identities0.IDENTITY_ENUNCIADO;
	public static final Identity<ImagemRecord, Integer> IDENTITY_IMAGEM = Identities0.IDENTITY_IMAGEM;
	public static final Identity<PalavraRecord, Integer> IDENTITY_PALAVRA = Identities0.IDENTITY_PALAVRA;
	public static final Identity<PlaylistRecord, Integer> IDENTITY_PLAYLIST = Identities0.IDENTITY_PLAYLIST;
	public static final Identity<RespostaRecord, Integer> IDENTITY_RESPOSTA = Identities0.IDENTITY_RESPOSTA;
	public static final Identity<SilabaRecord, Integer> IDENTITY_SILABA = Identities0.IDENTITY_SILABA;
	public static final Identity<TentativaRecord, Integer> IDENTITY_TENTATIVA = Identities0.IDENTITY_TENTATIVA;
	public static final Identity<TipoblocoRecord, Integer> IDENTITY_TIPOBLOCO = Identities0.IDENTITY_TIPOBLOCO;
	public static final Identity<TurmaRecord, Integer> IDENTITY_TURMA = Identities0.IDENTITY_TURMA;
	public static final Identity<VideoRecord, Integer> IDENTITY_VIDEO = Identities0.IDENTITY_VIDEO;

	// -------------------------------------------------------------------------
	// UNIQUE and PRIMARY KEY definitions
	// -------------------------------------------------------------------------

	public static final UniqueKey<AlternativaRecord> KEY_ALTERNATIVA_PRIMARY = UniqueKeys0.KEY_ALTERNATIVA_PRIMARY;
	public static final UniqueKey<AlunoRecord> KEY_ALUNO_PRIMARY = UniqueKeys0.KEY_ALUNO_PRIMARY;
	public static final UniqueKey<AudioRecord> KEY_AUDIO_PRIMARY = UniqueKeys0.KEY_AUDIO_PRIMARY;
	public static final UniqueKey<AudioPlaylistRecord> KEY_AUDIO_PLAYLIST_PRIMARY = UniqueKeys0.KEY_AUDIO_PLAYLIST_PRIMARY;
	public static final UniqueKey<AvaliacaoRecord> KEY_AVALIACAO_PRIMARY = UniqueKeys0.KEY_AVALIACAO_PRIMARY;
	public static final UniqueKey<AvaliacaoBlocoRecord> KEY_AVALIACAO_BLOCO_PRIMARY = UniqueKeys0.KEY_AVALIACAO_BLOCO_PRIMARY;
	public static final UniqueKey<BlocoRecord> KEY_BLOCO_PRIMARY = UniqueKeys0.KEY_BLOCO_PRIMARY;
	public static final UniqueKey<CategoriaRecord> KEY_CATEGORIA_PRIMARY = UniqueKeys0.KEY_CATEGORIA_PRIMARY;
	public static final UniqueKey<EnunciadoRecord> KEY_ENUNCIADO_PRIMARY = UniqueKeys0.KEY_ENUNCIADO_PRIMARY;
	public static final UniqueKey<ImagemRecord> KEY_IMAGEM_PRIMARY = UniqueKeys0.KEY_IMAGEM_PRIMARY;
	public static final UniqueKey<PalavraRecord> KEY_PALAVRA_PRIMARY = UniqueKeys0.KEY_PALAVRA_PRIMARY;
	public static final UniqueKey<PalavraSilabaRecord> KEY_PALAVRA_SILABA_PRIMARY = UniqueKeys0.KEY_PALAVRA_SILABA_PRIMARY;
	public static final UniqueKey<PlaylistRecord> KEY_PLAYLIST_PRIMARY = UniqueKeys0.KEY_PLAYLIST_PRIMARY;
	public static final UniqueKey<RealizaRecord> KEY_REALIZA_PRIMARY = UniqueKeys0.KEY_REALIZA_PRIMARY;
	public static final UniqueKey<RespostaRecord> KEY_RESPOSTA_PRIMARY = UniqueKeys0.KEY_RESPOSTA_PRIMARY;
	public static final UniqueKey<SilabaRecord> KEY_SILABA_PRIMARY = UniqueKeys0.KEY_SILABA_PRIMARY;
	public static final UniqueKey<TentativaRecord> KEY_TENTATIVA_PRIMARY = UniqueKeys0.KEY_TENTATIVA_PRIMARY;
	public static final UniqueKey<TipoblocoRecord> KEY_TIPOBLOCO_PRIMARY = UniqueKeys0.KEY_TIPOBLOCO_PRIMARY;
	public static final UniqueKey<TurmaRecord> KEY_TURMA_PRIMARY = UniqueKeys0.KEY_TURMA_PRIMARY;
	public static final UniqueKey<VideoRecord> KEY_VIDEO_PRIMARY = UniqueKeys0.KEY_VIDEO_PRIMARY;
	public static final UniqueKey<VideoPlaylistRecord> KEY_VIDEO_PLAYLIST_PRIMARY = UniqueKeys0.KEY_VIDEO_PLAYLIST_PRIMARY;

	// -------------------------------------------------------------------------
	// FOREIGN KEY definitions
	// -------------------------------------------------------------------------

	public static final ForeignKey<AlternativaRecord, TentativaRecord> FK_ALTERNATIVA_TENTATIVA1 = ForeignKeys0.FK_ALTERNATIVA_TENTATIVA1;
	public static final ForeignKey<AlternativaRecord, PalavraRecord> FK_ALTERNATIVA_PALAVRA1 = ForeignKeys0.FK_ALTERNATIVA_PALAVRA1;
	public static final ForeignKey<AudioPlaylistRecord, PlaylistRecord> FK_AUDIO_PLAYLIST_PLAYLIST1 = ForeignKeys0.FK_AUDIO_PLAYLIST_PLAYLIST1;
	public static final ForeignKey<AudioPlaylistRecord, AudioRecord> FK_AUDIO_PLAYLIST_AUDIO1 = ForeignKeys0.FK_AUDIO_PLAYLIST_AUDIO1;
	public static final ForeignKey<AvaliacaoBlocoRecord, AvaliacaoRecord> FK_AVALIACAO_BLOCO_AVALIACAO1 = ForeignKeys0.FK_AVALIACAO_BLOCO_AVALIACAO1;
	public static final ForeignKey<AvaliacaoBlocoRecord, BlocoRecord> FK_AVALIACAO_BLOCO_BLOCO1 = ForeignKeys0.FK_AVALIACAO_BLOCO_BLOCO1;
	public static final ForeignKey<BlocoRecord, TipoblocoRecord> FK_BLOCO_TIPOBLOCO1 = ForeignKeys0.FK_BLOCO_TIPOBLOCO1;
	public static final ForeignKey<EnunciadoRecord, PlaylistRecord> FK_ENUNCIADO_PLAYLIST1 = ForeignKeys0.FK_ENUNCIADO_PLAYLIST1;
	public static final ForeignKey<PalavraRecord, CategoriaRecord> FK_PALAVRA_CATEGORIA_PALAVRA1 = ForeignKeys0.FK_PALAVRA_CATEGORIA_PALAVRA1;
	public static final ForeignKey<PalavraRecord, AudioRecord> FK_PALAVRA_AUDIO1 = ForeignKeys0.FK_PALAVRA_AUDIO1;
	public static final ForeignKey<PalavraRecord, ImagemRecord> FK_PALAVRA_IMAGEM1 = ForeignKeys0.FK_PALAVRA_IMAGEM1;
	public static final ForeignKey<PalavraRecord, VideoRecord> FK_PALAVRA_VIDEO1 = ForeignKeys0.FK_PALAVRA_VIDEO1;
	public static final ForeignKey<PalavraSilabaRecord, PalavraRecord> FK_PALAVRA_SILABA_PALAVRA1 = ForeignKeys0.FK_PALAVRA_SILABA_PALAVRA1;
	public static final ForeignKey<PalavraSilabaRecord, SilabaRecord> FK_PALAVRA_SILABA_SILABA1 = ForeignKeys0.FK_PALAVRA_SILABA_SILABA1;
	public static final ForeignKey<RealizaRecord, AlunoRecord> FK_ALUNO_HAS_AVALIACAO_ALUNO1 = ForeignKeys0.FK_ALUNO_HAS_AVALIACAO_ALUNO1;
	public static final ForeignKey<RealizaRecord, AvaliacaoRecord> FK_ALUNO_HAS_AVALIACAO_AVALIACAO1 = ForeignKeys0.FK_ALUNO_HAS_AVALIACAO_AVALIACAO1;
	public static final ForeignKey<RespostaRecord, RealizaRecord> FK_RESPOSTA_REALIZA1 = ForeignKeys0.FK_RESPOSTA_REALIZA1;
	public static final ForeignKey<RespostaRecord, TentativaRecord> FK_RESPOSTA_TENTATIVA1 = ForeignKeys0.FK_RESPOSTA_TENTATIVA1;
	public static final ForeignKey<RespostaRecord, AlternativaRecord> FK_RESPOSTA_ALTERNATIVA1 = ForeignKeys0.FK_RESPOSTA_ALTERNATIVA1;
	public static final ForeignKey<TentativaRecord, BlocoRecord> FK_TENTATIVA_BLOCO1 = ForeignKeys0.FK_TENTATIVA_BLOCO1;
	public static final ForeignKey<TentativaRecord, EnunciadoRecord> FK_TENTATIVA_ENUNCIADO1 = ForeignKeys0.FK_TENTATIVA_ENUNCIADO1;
	public static final ForeignKey<VideoPlaylistRecord, VideoRecord> FK_VIDEO_PLAYLIST_VIDEO1 = ForeignKeys0.FK_VIDEO_PLAYLIST_VIDEO1;
	public static final ForeignKey<VideoPlaylistRecord, PlaylistRecord> FK_VIDEO_PLAYLIST_PLAYLIST1 = ForeignKeys0.FK_VIDEO_PLAYLIST_PLAYLIST1;

	// -------------------------------------------------------------------------
	// [#1459] distribute members to avoid static initialisers > 64kb
	// -------------------------------------------------------------------------

	private static class Identities0 extends AbstractKeys {
		public static Identity<AlternativaRecord, Integer> IDENTITY_ALTERNATIVA = createIdentity(Alternativa.ALTERNATIVA, Alternativa.ALTERNATIVA.IDALTERNATIVA);
		public static Identity<AlunoRecord, Integer> IDENTITY_ALUNO = createIdentity(Aluno.ALUNO, Aluno.ALUNO.IDALUNO);
		public static Identity<AudioRecord, Integer> IDENTITY_AUDIO = createIdentity(Audio.AUDIO, Audio.AUDIO.IDAUDIO);
		public static Identity<AvaliacaoRecord, Integer> IDENTITY_AVALIACAO = createIdentity(Avaliacao.AVALIACAO, Avaliacao.AVALIACAO.IDAVALIACAO);
		public static Identity<BlocoRecord, Integer> IDENTITY_BLOCO = createIdentity(Bloco.BLOCO, Bloco.BLOCO.IDBLOCO);
		public static Identity<CategoriaRecord, Integer> IDENTITY_CATEGORIA = createIdentity(Categoria.CATEGORIA, Categoria.CATEGORIA.IDCATEGORIA);
		public static Identity<EnunciadoRecord, Integer> IDENTITY_ENUNCIADO = createIdentity(Enunciado.ENUNCIADO, Enunciado.ENUNCIADO.IDENUNCIADO);
		public static Identity<ImagemRecord, Integer> IDENTITY_IMAGEM = createIdentity(Imagem.IMAGEM, Imagem.IMAGEM.IDIMAGEM);
		public static Identity<PalavraRecord, Integer> IDENTITY_PALAVRA = createIdentity(Palavra.PALAVRA, Palavra.PALAVRA.IDPALAVRA);
		public static Identity<PlaylistRecord, Integer> IDENTITY_PLAYLIST = createIdentity(Playlist.PLAYLIST, Playlist.PLAYLIST.IDPLAYLIST);
		public static Identity<RespostaRecord, Integer> IDENTITY_RESPOSTA = createIdentity(Resposta.RESPOSTA, Resposta.RESPOSTA.IDRESPOSTA);
		public static Identity<SilabaRecord, Integer> IDENTITY_SILABA = createIdentity(Silaba.SILABA, Silaba.SILABA.IDSILABA);
		public static Identity<TentativaRecord, Integer> IDENTITY_TENTATIVA = createIdentity(Tentativa.TENTATIVA, Tentativa.TENTATIVA.IDTENTATIVA);
		public static Identity<TipoblocoRecord, Integer> IDENTITY_TIPOBLOCO = createIdentity(Tipobloco.TIPOBLOCO, Tipobloco.TIPOBLOCO.IDTIPOBLOCO);
		public static Identity<TurmaRecord, Integer> IDENTITY_TURMA = createIdentity(Turma.TURMA, Turma.TURMA.IDTURMA);
		public static Identity<VideoRecord, Integer> IDENTITY_VIDEO = createIdentity(Video.VIDEO, Video.VIDEO.IDVIDEO);
	}

	private static class UniqueKeys0 extends AbstractKeys {
		public static final UniqueKey<AlternativaRecord> KEY_ALTERNATIVA_PRIMARY = createUniqueKey(Alternativa.ALTERNATIVA, Alternativa.ALTERNATIVA.IDALTERNATIVA, Alternativa.ALTERNATIVA.PALAVRA_IDPALAVRA, Alternativa.ALTERNATIVA.PALAVRA_IDCATEGORIA, Alternativa.ALTERNATIVA.PALAVRA_IDAUDIO, Alternativa.ALTERNATIVA.PALAVRA_IDIMAGEM);
		public static final UniqueKey<AlunoRecord> KEY_ALUNO_PRIMARY = createUniqueKey(Aluno.ALUNO, Aluno.ALUNO.IDALUNO);
		public static final UniqueKey<AudioRecord> KEY_AUDIO_PRIMARY = createUniqueKey(Audio.AUDIO, Audio.AUDIO.IDAUDIO);
		public static final UniqueKey<AudioPlaylistRecord> KEY_AUDIO_PLAYLIST_PRIMARY = createUniqueKey(AudioPlaylist.AUDIO_PLAYLIST, AudioPlaylist.AUDIO_PLAYLIST.IDPLAYLIST, AudioPlaylist.AUDIO_PLAYLIST.IDAUDIO);
		public static final UniqueKey<AvaliacaoRecord> KEY_AVALIACAO_PRIMARY = createUniqueKey(Avaliacao.AVALIACAO, Avaliacao.AVALIACAO.IDAVALIACAO);
		public static final UniqueKey<AvaliacaoBlocoRecord> KEY_AVALIACAO_BLOCO_PRIMARY = createUniqueKey(AvaliacaoBloco.AVALIACAO_BLOCO, AvaliacaoBloco.AVALIACAO_BLOCO.IDAVALIACAO, AvaliacaoBloco.AVALIACAO_BLOCO.IDBLOCO);
		public static final UniqueKey<BlocoRecord> KEY_BLOCO_PRIMARY = createUniqueKey(Bloco.BLOCO, Bloco.BLOCO.IDBLOCO);
		public static final UniqueKey<CategoriaRecord> KEY_CATEGORIA_PRIMARY = createUniqueKey(Categoria.CATEGORIA, Categoria.CATEGORIA.IDCATEGORIA);
		public static final UniqueKey<EnunciadoRecord> KEY_ENUNCIADO_PRIMARY = createUniqueKey(Enunciado.ENUNCIADO, Enunciado.ENUNCIADO.IDENUNCIADO);
		public static final UniqueKey<ImagemRecord> KEY_IMAGEM_PRIMARY = createUniqueKey(Imagem.IMAGEM, Imagem.IMAGEM.IDIMAGEM);
		public static final UniqueKey<PalavraRecord> KEY_PALAVRA_PRIMARY = createUniqueKey(Palavra.PALAVRA, Palavra.PALAVRA.IDPALAVRA, Palavra.PALAVRA.IDCATEGORIA, Palavra.PALAVRA.IDAUDIO, Palavra.PALAVRA.IDIMAGEM);
		public static final UniqueKey<PalavraSilabaRecord> KEY_PALAVRA_SILABA_PRIMARY = createUniqueKey(PalavraSilaba.PALAVRA_SILABA, PalavraSilaba.PALAVRA_SILABA.PALAVRA_IDPALAVRA, PalavraSilaba.PALAVRA_SILABA.SILABA_IDSILABA);
		public static final UniqueKey<PlaylistRecord> KEY_PLAYLIST_PRIMARY = createUniqueKey(Playlist.PLAYLIST, Playlist.PLAYLIST.IDPLAYLIST);
		public static final UniqueKey<RealizaRecord> KEY_REALIZA_PRIMARY = createUniqueKey(Realiza.REALIZA, Realiza.REALIZA.IDALUNO, Realiza.REALIZA.IDAVALIACAO);
		public static final UniqueKey<RespostaRecord> KEY_RESPOSTA_PRIMARY = createUniqueKey(Resposta.RESPOSTA, Resposta.RESPOSTA.IDRESPOSTA, Resposta.RESPOSTA.REALIZA_IDALUNO, Resposta.RESPOSTA.REALIZA_IDAVALIACAO, Resposta.RESPOSTA.IDTENTATIVA, Resposta.RESPOSTA.IDALTERNATIVA);
		public static final UniqueKey<SilabaRecord> KEY_SILABA_PRIMARY = createUniqueKey(Silaba.SILABA, Silaba.SILABA.IDSILABA);
		public static final UniqueKey<TentativaRecord> KEY_TENTATIVA_PRIMARY = createUniqueKey(Tentativa.TENTATIVA, Tentativa.TENTATIVA.IDTENTATIVA);
		public static final UniqueKey<TipoblocoRecord> KEY_TIPOBLOCO_PRIMARY = createUniqueKey(Tipobloco.TIPOBLOCO, Tipobloco.TIPOBLOCO.IDTIPOBLOCO);
		public static final UniqueKey<TurmaRecord> KEY_TURMA_PRIMARY = createUniqueKey(Turma.TURMA, Turma.TURMA.IDTURMA);
		public static final UniqueKey<VideoRecord> KEY_VIDEO_PRIMARY = createUniqueKey(Video.VIDEO, Video.VIDEO.IDVIDEO);
		public static final UniqueKey<VideoPlaylistRecord> KEY_VIDEO_PLAYLIST_PRIMARY = createUniqueKey(VideoPlaylist.VIDEO_PLAYLIST, VideoPlaylist.VIDEO_PLAYLIST.IDPLAYLIST, VideoPlaylist.VIDEO_PLAYLIST.IDVIDEO);
	}

	private static class ForeignKeys0 extends AbstractKeys {
		public static final ForeignKey<AlternativaRecord, TentativaRecord> FK_ALTERNATIVA_TENTATIVA1 = createForeignKey(DAO.mysql.generatedclasses.Keys.KEY_TENTATIVA_PRIMARY, Alternativa.ALTERNATIVA, Alternativa.ALTERNATIVA.IDTENTATIVA);
		public static final ForeignKey<AlternativaRecord, PalavraRecord> FK_ALTERNATIVA_PALAVRA1 = createForeignKey(DAO.mysql.generatedclasses.Keys.KEY_PALAVRA_PRIMARY, Alternativa.ALTERNATIVA, Alternativa.ALTERNATIVA.PALAVRA_IDPALAVRA, Alternativa.ALTERNATIVA.PALAVRA_IDCATEGORIA, Alternativa.ALTERNATIVA.PALAVRA_IDAUDIO, Alternativa.ALTERNATIVA.PALAVRA_IDIMAGEM);
		public static final ForeignKey<AudioPlaylistRecord, PlaylistRecord> FK_AUDIO_PLAYLIST_PLAYLIST1 = createForeignKey(DAO.mysql.generatedclasses.Keys.KEY_PLAYLIST_PRIMARY, AudioPlaylist.AUDIO_PLAYLIST, AudioPlaylist.AUDIO_PLAYLIST.IDPLAYLIST);
		public static final ForeignKey<AudioPlaylistRecord, AudioRecord> FK_AUDIO_PLAYLIST_AUDIO1 = createForeignKey(DAO.mysql.generatedclasses.Keys.KEY_AUDIO_PRIMARY, AudioPlaylist.AUDIO_PLAYLIST, AudioPlaylist.AUDIO_PLAYLIST.IDAUDIO);
		public static final ForeignKey<AvaliacaoBlocoRecord, AvaliacaoRecord> FK_AVALIACAO_BLOCO_AVALIACAO1 = createForeignKey(DAO.mysql.generatedclasses.Keys.KEY_AVALIACAO_PRIMARY, AvaliacaoBloco.AVALIACAO_BLOCO, AvaliacaoBloco.AVALIACAO_BLOCO.IDAVALIACAO);
		public static final ForeignKey<AvaliacaoBlocoRecord, BlocoRecord> FK_AVALIACAO_BLOCO_BLOCO1 = createForeignKey(DAO.mysql.generatedclasses.Keys.KEY_BLOCO_PRIMARY, AvaliacaoBloco.AVALIACAO_BLOCO, AvaliacaoBloco.AVALIACAO_BLOCO.IDBLOCO);
		public static final ForeignKey<BlocoRecord, TipoblocoRecord> FK_BLOCO_TIPOBLOCO1 = createForeignKey(DAO.mysql.generatedclasses.Keys.KEY_TIPOBLOCO_PRIMARY, Bloco.BLOCO, Bloco.BLOCO.IDTIPOBLOCO);
		public static final ForeignKey<EnunciadoRecord, PlaylistRecord> FK_ENUNCIADO_PLAYLIST1 = createForeignKey(DAO.mysql.generatedclasses.Keys.KEY_PLAYLIST_PRIMARY, Enunciado.ENUNCIADO, Enunciado.ENUNCIADO.IDPLAYLIST);
		public static final ForeignKey<PalavraRecord, CategoriaRecord> FK_PALAVRA_CATEGORIA_PALAVRA1 = createForeignKey(DAO.mysql.generatedclasses.Keys.KEY_CATEGORIA_PRIMARY, Palavra.PALAVRA, Palavra.PALAVRA.IDCATEGORIA);
		public static final ForeignKey<PalavraRecord, AudioRecord> FK_PALAVRA_AUDIO1 = createForeignKey(DAO.mysql.generatedclasses.Keys.KEY_AUDIO_PRIMARY, Palavra.PALAVRA, Palavra.PALAVRA.IDAUDIO);
		public static final ForeignKey<PalavraRecord, ImagemRecord> FK_PALAVRA_IMAGEM1 = createForeignKey(DAO.mysql.generatedclasses.Keys.KEY_IMAGEM_PRIMARY, Palavra.PALAVRA, Palavra.PALAVRA.IDIMAGEM);
		public static final ForeignKey<PalavraRecord, VideoRecord> FK_PALAVRA_VIDEO1 = createForeignKey(DAO.mysql.generatedclasses.Keys.KEY_VIDEO_PRIMARY, Palavra.PALAVRA, Palavra.PALAVRA.IDVIDEO);
		public static final ForeignKey<PalavraSilabaRecord, PalavraRecord> FK_PALAVRA_SILABA_PALAVRA1 = createForeignKey(DAO.mysql.generatedclasses.Keys.KEY_PALAVRA_PRIMARY, PalavraSilaba.PALAVRA_SILABA, PalavraSilaba.PALAVRA_SILABA.PALAVRA_IDPALAVRA);
		public static final ForeignKey<PalavraSilabaRecord, SilabaRecord> FK_PALAVRA_SILABA_SILABA1 = createForeignKey(DAO.mysql.generatedclasses.Keys.KEY_SILABA_PRIMARY, PalavraSilaba.PALAVRA_SILABA, PalavraSilaba.PALAVRA_SILABA.SILABA_IDSILABA);
		public static final ForeignKey<RealizaRecord, AlunoRecord> FK_ALUNO_HAS_AVALIACAO_ALUNO1 = createForeignKey(DAO.mysql.generatedclasses.Keys.KEY_ALUNO_PRIMARY, Realiza.REALIZA, Realiza.REALIZA.IDALUNO);
		public static final ForeignKey<RealizaRecord, AvaliacaoRecord> FK_ALUNO_HAS_AVALIACAO_AVALIACAO1 = createForeignKey(DAO.mysql.generatedclasses.Keys.KEY_AVALIACAO_PRIMARY, Realiza.REALIZA, Realiza.REALIZA.IDAVALIACAO);
		public static final ForeignKey<RespostaRecord, RealizaRecord> FK_RESPOSTA_REALIZA1 = createForeignKey(DAO.mysql.generatedclasses.Keys.KEY_REALIZA_PRIMARY, Resposta.RESPOSTA, Resposta.RESPOSTA.REALIZA_IDALUNO, Resposta.RESPOSTA.REALIZA_IDAVALIACAO);
		public static final ForeignKey<RespostaRecord, TentativaRecord> FK_RESPOSTA_TENTATIVA1 = createForeignKey(DAO.mysql.generatedclasses.Keys.KEY_TENTATIVA_PRIMARY, Resposta.RESPOSTA, Resposta.RESPOSTA.IDTENTATIVA);
		public static final ForeignKey<RespostaRecord, AlternativaRecord> FK_RESPOSTA_ALTERNATIVA1 = createForeignKey(DAO.mysql.generatedclasses.Keys.KEY_ALTERNATIVA_PRIMARY, Resposta.RESPOSTA, Resposta.RESPOSTA.IDALTERNATIVA);
		public static final ForeignKey<TentativaRecord, BlocoRecord> FK_TENTATIVA_BLOCO1 = createForeignKey(DAO.mysql.generatedclasses.Keys.KEY_BLOCO_PRIMARY, Tentativa.TENTATIVA, Tentativa.TENTATIVA.IDBLOCO);
		public static final ForeignKey<TentativaRecord, EnunciadoRecord> FK_TENTATIVA_ENUNCIADO1 = createForeignKey(DAO.mysql.generatedclasses.Keys.KEY_ENUNCIADO_PRIMARY, Tentativa.TENTATIVA, Tentativa.TENTATIVA.IDENUNCIADO);
		public static final ForeignKey<VideoPlaylistRecord, VideoRecord> FK_VIDEO_PLAYLIST_VIDEO1 = createForeignKey(DAO.mysql.generatedclasses.Keys.KEY_VIDEO_PRIMARY, VideoPlaylist.VIDEO_PLAYLIST, VideoPlaylist.VIDEO_PLAYLIST.IDVIDEO);
		public static final ForeignKey<VideoPlaylistRecord, PlaylistRecord> FK_VIDEO_PLAYLIST_PLAYLIST1 = createForeignKey(DAO.mysql.generatedclasses.Keys.KEY_PLAYLIST_PRIMARY, VideoPlaylist.VIDEO_PLAYLIST, VideoPlaylist.VIDEO_PLAYLIST.IDPLAYLIST);
	}
}
