/**
 * This class is generated by jOOQ
 */
package DAO.mysql.generatedclasses;


import DAO.mysql.generatedclasses.tables.*;

import javax.annotation.Generated;


/**
 * Convenience access to all tables in ensinoindividualizado
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.7.0"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

	/**
	 * The table ensinoindividualizado.alternativa
	 */
	public static final Alternativa ALTERNATIVA = DAO.mysql.generatedclasses.tables.Alternativa.ALTERNATIVA;

	/**
	 * The table ensinoindividualizado.aluno
	 */
	public static final Aluno ALUNO = DAO.mysql.generatedclasses.tables.Aluno.ALUNO;

	/**
	 * The table ensinoindividualizado.audio
	 */
	public static final Audio AUDIO = DAO.mysql.generatedclasses.tables.Audio.AUDIO;

	/**
	 * The table ensinoindividualizado.audio_playlist
	 */
	public static final AudioPlaylist AUDIO_PLAYLIST = DAO.mysql.generatedclasses.tables.AudioPlaylist.AUDIO_PLAYLIST;

	/**
	 * The table ensinoindividualizado.avaliacao
	 */
	public static final Avaliacao AVALIACAO = DAO.mysql.generatedclasses.tables.Avaliacao.AVALIACAO;

	/**
	 * The table ensinoindividualizado.avaliacao_bloco
	 */
	public static final AvaliacaoBloco AVALIACAO_BLOCO = DAO.mysql.generatedclasses.tables.AvaliacaoBloco.AVALIACAO_BLOCO;

	/**
	 * The table ensinoindividualizado.bloco
	 */
	public static final Bloco BLOCO = DAO.mysql.generatedclasses.tables.Bloco.BLOCO;

	/**
	 * The table ensinoindividualizado.categoria
	 */
	public static final Categoria CATEGORIA = DAO.mysql.generatedclasses.tables.Categoria.CATEGORIA;

	/**
	 * The table ensinoindividualizado.enunciado
	 */
	public static final Enunciado ENUNCIADO = DAO.mysql.generatedclasses.tables.Enunciado.ENUNCIADO;

	/**
	 * The table ensinoindividualizado.imagem
	 */
	public static final Imagem IMAGEM = DAO.mysql.generatedclasses.tables.Imagem.IMAGEM;

	/**
	 * The table ensinoindividualizado.palavra
	 */
	public static final Palavra PALAVRA = DAO.mysql.generatedclasses.tables.Palavra.PALAVRA;

	/**
	 * The table ensinoindividualizado.palavra_silaba
	 */
	public static final PalavraSilaba PALAVRA_SILABA = DAO.mysql.generatedclasses.tables.PalavraSilaba.PALAVRA_SILABA;

	/**
	 * The table ensinoindividualizado.playlist
	 */
	public static final Playlist PLAYLIST = DAO.mysql.generatedclasses.tables.Playlist.PLAYLIST;

	/**
	 * The table ensinoindividualizado.realiza
	 */
	public static final Realiza REALIZA = DAO.mysql.generatedclasses.tables.Realiza.REALIZA;

	/**
	 * The table ensinoindividualizado.resposta
	 */
	public static final Resposta RESPOSTA = DAO.mysql.generatedclasses.tables.Resposta.RESPOSTA;

	/**
	 * The table ensinoindividualizado.silaba
	 */
	public static final Silaba SILABA = DAO.mysql.generatedclasses.tables.Silaba.SILABA;

	/**
	 * The table ensinoindividualizado.tentativa
	 */
	public static final Tentativa TENTATIVA = DAO.mysql.generatedclasses.tables.Tentativa.TENTATIVA;

	/**
	 * The table ensinoindividualizado.tipobloco
	 */
	public static final Tipobloco TIPOBLOCO = DAO.mysql.generatedclasses.tables.Tipobloco.TIPOBLOCO;

	/**
	 * The table ensinoindividualizado.turma
	 */
	public static final Turma TURMA = DAO.mysql.generatedclasses.tables.Turma.TURMA;

	/**
	 * The table ensinoindividualizado.video
	 */
	public static final Video VIDEO = DAO.mysql.generatedclasses.tables.Video.VIDEO;

	/**
	 * The table ensinoindividualizado.video_playlist
	 */
	public static final VideoPlaylist VIDEO_PLAYLIST = DAO.mysql.generatedclasses.tables.VideoPlaylist.VIDEO_PLAYLIST;
}
